-- Trigger para populamento de Sequence | Tabela: PATH
CREATE OR REPLACE TRIGGER CLARO.TRG_BI_PATH
BEFORE INSERT ON CLARO.PATH
FOR EACH ROW
BEGIN
  IF :NEW.ID_PATH IS NULL THEN
    SELECT CLARO.id_generator.NEXTVAL INTO :NEW.ID_PATH FROM DUAL;
  END IF;
END;
/
