-- Trigger para populamento de Sequence | Tabela: STP_CFG
CREATE OR REPLACE TRIGGER TRG_BI_STP_CFG
BEFORE INSERT ON STP_CFG
FOR EACH ROW
BEGIN
  IF :NEW.ID_STP_CFG IS NULL THEN
    SELECT id_generator.NEXTVAL INTO :NEW.ID_STP_CFG FROM DUAL;
  END IF;
END;
/
