-- Trigger para populamento de Sequence | Tabela: TIME_SLOT
CREATE OR REPLACE TRIGGER CLARO.TRG_BI_TIME_SLOT
BEFORE INSERT ON CLARO.TIME_SLOT
FOR EACH ROW
BEGIN
  IF :NEW.ID_TIME_SLOT IS NULL THEN
    SELECT CLARO.id_generator.NEXTVAL INTO :NEW.ID_TIME_SLOT FROM DUAL;
  END IF;
END;
/
