-- Trigger para populamento de Sequence | Tabela: TB___PROXIES__TB
CREATE OR REPLACE TRIGGER TRG_BI_TB___PROXIES__TB
BEFORE INSERT ON TB___PROXIES__TB
FOR EACH ROW
BEGIN
  IF :NEW.CL___PROXY_CODE__CL IS NULL THEN
    SELECT PROXY_CODE_GEN.NEXTVAL INTO :NEW.CL___PROXY_CODE__CL FROM DUAL;
  END IF;
END;
/
