-- Trigger para populamento de Sequence | Tabela: CIRCUIT_PORT_END
CREATE OR REPLACE TRIGGER CLARO.TRG_BI_CIRCUIT_PORT_END
BEFORE INSERT ON CLARO.CIRCUIT_PORT_END
FOR EACH ROW
BEGIN
  IF :NEW.ID_CIRCUIT_PORT_END IS NULL THEN
    SELECT CLARO.id_generator.NEXTVAL INTO :NEW.ID_CIRCUIT_PORT_END FROM DUAL;
  END IF;
END;
/
