-- Trigger para populamento de Sequence | Tabela: GRAPHIC
CREATE OR REPLACE TRIGGER CLARO.TRG_BI_GRAPHIC
BEFORE INSERT ON CLARO.GRAPHIC
FOR EACH ROW
BEGIN
  IF :NEW.ID_GRAPHIC IS NULL THEN
    SELECT CLARO.id_generator.NEXTVAL INTO :NEW.ID_GRAPHIC FROM DUAL;
  END IF;
END;
/
