-- Trigger para populamento de Sequence | Tabela: CIRCUIT_FILTER
CREATE OR REPLACE TRIGGER CLARO.TRG_BI_CIRCUIT_FILTER
BEFORE INSERT ON CLARO.CIRCUIT_FILTER
FOR EACH ROW
BEGIN
  IF :NEW.ID_CIRCUIT_FILTER IS NULL THEN
    SELECT CLARO.id_generator.NEXTVAL INTO :NEW.ID_CIRCUIT_FILTER FROM DUAL;
  END IF;
END;
/
