-- Trigger para populamento de Sequence | Tabela: PORT_PATH_SECTION
CREATE OR REPLACE TRIGGER CLARO.TRG_BI_PORT_PATH_SECTION
BEFORE INSERT ON CLARO.PORT_PATH_SECTION
FOR EACH ROW
BEGIN
  IF :NEW.ID_PORT_PATH_SECTION IS NULL THEN
    SELECT CLARO.id_generator.NEXTVAL INTO :NEW.ID_PORT_PATH_SECTION FROM DUAL;
  END IF;
END;
/
