-- Trigger para populamento de Sequence | Tabela: PATH_SECTION
CREATE OR REPLACE TRIGGER CLARO.TRG_BI_PATH_SECTION
BEFORE INSERT ON CLARO.PATH_SECTION
FOR EACH ROW
BEGIN
  IF :NEW.ID_PATH_SECTION IS NULL THEN
    SELECT CLARO.id_generator.NEXTVAL INTO :NEW.ID_PATH_SECTION FROM DUAL;
  END IF;
END;
/
