-- Trigger para populamento de Sequence | Tabela: TB___PROXIES__TB
CREATE OR REPLACE TRIGGER CLARO.TRG_BI_TB___PROXIES__TB
BEFORE INSERT ON CLARO.TB___PROXIES__TB
FOR EACH ROW
BEGIN
  IF :NEW.CL___PROXY_CODE__CL IS NULL THEN
    SELECT CLARO.PROXY_CODE_GEN.NEXTVAL INTO :NEW.CL___PROXY_CODE__CL FROM DUAL;
  END IF;
END;
/
