-- Trigger para populamento de Sequence | Tabela: NODE
CREATE OR REPLACE TRIGGER TRG_BI_NODE
BEFORE INSERT ON NODE
FOR EACH ROW
BEGIN
  IF :NEW.ID_NODE IS NULL THEN
    SELECT id_generator.NEXTVAL INTO :NEW.ID_NODE FROM DUAL;
  END IF;
END;
/
