-- Trigger para populamento de Sequence | Tabela: MATRIX
CREATE OR REPLACE TRIGGER TRG_BI_MATRIX
BEFORE INSERT ON MATRIX
FOR EACH ROW
BEGIN
  IF :NEW.ID_MATRIX IS NULL THEN
    SELECT MATRIX_ID_GEN.NEXTVAL INTO :NEW.ID_MATRIX FROM DUAL;
  END IF;
END;
/
