-- Trigger para populamento de Sequence | Tabela: CIRCUIT_END
CREATE OR REPLACE TRIGGER TRG_BI_CIRCUIT_END
BEFORE INSERT ON CIRCUIT_END
FOR EACH ROW
BEGIN
  IF :NEW.ID_CIRCUIT_END IS NULL THEN
    SELECT id_generator.NEXTVAL INTO :NEW.ID_CIRCUIT_END FROM DUAL;
  END IF;
END;
/
