-- Trigger para populamento de Sequence | Tabela: PATH_SECTION
CREATE OR REPLACE TRIGGER TRG_BI_PATH_SECTION
BEFORE INSERT ON PATH_SECTION
FOR EACH ROW
BEGIN
  IF :NEW.ID_PATH_SECTION IS NULL THEN
    SELECT id_generator.NEXTVAL INTO :NEW.ID_PATH_SECTION FROM DUAL;
  END IF;
END;
/
