-- Trigger para populamento de Sequence | Tabela: CUSTOMER
CREATE OR REPLACE TRIGGER CLARO.TRG_BI_CUSTOMER
BEFORE INSERT ON CLARO.CUSTOMER
FOR EACH ROW
BEGIN
  IF :NEW.ID_CUSTOMER IS NULL THEN
    SELECT CLARO.CUSTOMER_ID_GEN.NEXTVAL INTO :NEW.ID_CUSTOMER FROM DUAL;
  END IF;
END;
/
