-- Trigger para populamento de Sequence | Tabela: SNMPV1_2
CREATE OR REPLACE TRIGGER CLARO.TRG_BI_SNMPV1_2
BEFORE INSERT ON CLARO.SNMPV1_2
FOR EACH ROW
BEGIN
  IF :NEW.ID_SNMPV1_2 IS NULL THEN
    SELECT CLARO.id_generator.NEXTVAL INTO :NEW.ID_SNMPV1_2 FROM DUAL;
  END IF;
END;
/
