-- Trigger para populamento de Sequence | Tabela: NODE
CREATE OR REPLACE TRIGGER CLARO.TRG_BI_NODE
BEFORE INSERT ON CLARO.NODE
FOR EACH ROW
BEGIN
  IF :NEW.ID_NODE IS NULL THEN
    SELECT CLARO.id_generator.NEXTVAL INTO :NEW.ID_NODE FROM DUAL;
  END IF;
END;
/
