-- Trigger para populamento de Sequence | Tabela: SNMP
CREATE OR REPLACE TRIGGER CLARO.TRG_BI_SNMP
BEFORE INSERT ON CLARO.SNMP
FOR EACH ROW
BEGIN
  IF :NEW.ID_SNMP IS NULL THEN
    SELECT CLARO.id_generator.NEXTVAL INTO :NEW.ID_SNMP FROM DUAL;
  END IF;
END;
/
