-- Trigger para populamento de Sequence | Tabela: CIRCUIT_PATH_SECTION
CREATE OR REPLACE TRIGGER TRG_BI_CIRCUIT_PATH_SECTION
BEFORE INSERT ON CIRCUIT_PATH_SECTION
FOR EACH ROW
BEGIN
  IF :NEW.ID_CIRCUIT_PATH_SECTION IS NULL THEN
    SELECT id_generator.NEXTVAL INTO :NEW.ID_CIRCUIT_PATH_SECTION FROM DUAL;
  END IF;
END;
/
