-- Trigger para populamento de Sequence | Tabela: SDH_MAPPING_DM800
CREATE OR REPLACE TRIGGER CLARO.TRG_BI_SDH_MAPPING_DM800
BEFORE INSERT ON CLARO.SDH_MAPPING_DM800
FOR EACH ROW
BEGIN
  IF :NEW.ID_SDH_MAPPING_DM800 IS NULL THEN
    SELECT CLARO.sdh_mapping_dm800_gen.NEXTVAL INTO :NEW.ID_SDH_MAPPING_DM800 FROM DUAL;
  END IF;
END;
/
