-- Trigger para populamento de Sequence | Tabela: TIME_SLOT
CREATE OR REPLACE TRIGGER TRG_BI_TIME_SLOT
BEFORE INSERT ON TIME_SLOT
FOR EACH ROW
BEGIN
  IF :NEW.ID_TIME_SLOT IS NULL THEN
    SELECT id_generator.NEXTVAL INTO :NEW.ID_TIME_SLOT FROM DUAL;
  END IF;
END;
/
