-- Trigger para populamento de Sequence | Tabela: CIRCUIT_FILTER
CREATE OR REPLACE TRIGGER TRG_BI_CIRCUIT_FILTER
BEFORE INSERT ON CIRCUIT_FILTER
FOR EACH ROW
BEGIN
  IF :NEW.ID_CIRCUIT_FILTER IS NULL THEN
    SELECT id_generator.NEXTVAL INTO :NEW.ID_CIRCUIT_FILTER FROM DUAL;
  END IF;
END;
/
