-- Trigger para populamento de Sequence | Tabela: DEVICE_DATA_FILE
CREATE OR REPLACE TRIGGER TRG_BI_DEVICE_DATA_FILE
BEFORE INSERT ON DEVICE_DATA_FILE
FOR EACH ROW
BEGIN
  IF :NEW.ID_DEVICE_DATA_FILE IS NULL THEN
    SELECT device_data_file_seq.NEXTVAL INTO :NEW.ID_DEVICE_DATA_FILE FROM DUAL;
  END IF;
END;
/
