-- Trigger para populamento de Sequence | Tabela: CIRCUIT_PORT_END
CREATE OR REPLACE TRIGGER TRG_BI_CIRCUIT_PORT_END
BEFORE INSERT ON CIRCUIT_PORT_END
FOR EACH ROW
BEGIN
  IF :NEW.ID_CIRCUIT_PORT_END IS NULL THEN
    SELECT id_generator.NEXTVAL INTO :NEW.ID_CIRCUIT_PORT_END FROM DUAL;
  END IF;
END;
/
