-- Trigger para populamento de Sequence | Tabela: PATH
CREATE OR REPLACE TRIGGER TRG_BI_PATH
BEFORE INSERT ON PATH
FOR EACH ROW
BEGIN
  IF :NEW.ID_PATH IS NULL THEN
    SELECT id_generator.NEXTVAL INTO :NEW.ID_PATH FROM DUAL;
  END IF;
END;
/
