-- Trigger para populamento de Sequence | Tabela: SDH_MAPPING
CREATE OR REPLACE TRIGGER CLARO.TRG_BI_SDH_MAPPING
BEFORE INSERT ON CLARO.SDH_MAPPING
FOR EACH ROW
BEGIN
  IF :NEW.ID_SDH_MAPPING IS NULL THEN
    SELECT CLARO.SDH_MAPPING_GEN.NEXTVAL INTO :NEW.ID_SDH_MAPPING FROM DUAL;
  END IF;
END;
/
