-- Trigger para populamento de Sequence | Tabela: CIRCUIT_FILTER_PROPERTY
CREATE OR REPLACE TRIGGER CLARO.TRG_BI_CIRCUIT_FILTER_PROPERTY
BEFORE INSERT ON CLARO.CIRCUIT_FILTER_PROPERTY
FOR EACH ROW
BEGIN
  IF :NEW.ID_CIRCUIT_FILTER_PROPERTY IS NULL THEN
    SELECT CLARO.id_generator.NEXTVAL INTO :NEW.ID_CIRCUIT_FILTER_PROPERTY FROM DUAL;
  END IF;
END;
/
