-- Trigger para populamento de Sequence | Tabela: VLAN_CFG
CREATE OR REPLACE TRIGGER TRG_BI_VLAN_CFG
BEFORE INSERT ON VLAN_CFG
FOR EACH ROW
BEGIN
  IF :NEW.ID_VLAN_CFG IS NULL THEN
    SELECT id_generator.NEXTVAL INTO :NEW.ID_VLAN_CFG FROM DUAL;
  END IF;
END;
/
