-- Trigger para populamento de Sequence | Tabela: LINK
CREATE OR REPLACE TRIGGER CLARO.TRG_BI_LINK
BEFORE INSERT ON CLARO.LINK
FOR EACH ROW
BEGIN
  IF :NEW.ID_LINK IS NULL THEN
    SELECT CLARO.id_generator.NEXTVAL INTO :NEW.ID_LINK FROM DUAL;
  END IF;
END;
/
