-- Trigger para populamento de Sequence | Tabela: SERVICE
CREATE OR REPLACE TRIGGER CLARO.TRG_BI_SERVICE
BEFORE INSERT ON CLARO.SERVICE
FOR EACH ROW
BEGIN
  IF :NEW.ID_SERVICE IS NULL THEN
    SELECT CLARO.SERVICE_ID_SEQ.NEXTVAL INTO :NEW.ID_SERVICE FROM DUAL;
  END IF;
END;
/
