-- Trigger para populamento de Sequence | Tabela: SNMP
CREATE OR REPLACE TRIGGER TRG_BI_SNMP
BEFORE INSERT ON SNMP
FOR EACH ROW
BEGIN
  IF :NEW.ID_SNMP IS NULL THEN
    SELECT id_generator.NEXTVAL INTO :NEW.ID_SNMP FROM DUAL;
  END IF;
END;
/
