-- Trigger para populamento de Sequence | Tabela: CIRCUIT_PATH_SECTION
CREATE OR REPLACE TRIGGER CLARO.TRG_BI_CIRCUIT_PATH_SECTION
BEFORE INSERT ON CLARO.CIRCUIT_PATH_SECTION
FOR EACH ROW
BEGIN
  IF :NEW.ID_CIRCUIT_PATH_SECTION IS NULL THEN
    SELECT CLARO.id_generator.NEXTVAL INTO :NEW.ID_CIRCUIT_PATH_SECTION FROM DUAL;
  END IF;
END;
/
