-- Trigger para populamento de Sequence | Tabela: SERVICE
CREATE OR REPLACE TRIGGER TRG_BI_SERVICE
BEFORE INSERT ON SERVICE
FOR EACH ROW
BEGIN
  IF :NEW.ID_SERVICE IS NULL THEN
    SELECT SERVICE_ID_SEQ.NEXTVAL INTO :NEW.ID_SERVICE FROM DUAL;
  END IF;
END;
/
