-- Trigger para populamento de Sequence | Tabela: VLAN_CFG
CREATE OR REPLACE TRIGGER CLARO.TRG_BI_VLAN_CFG
BEFORE INSERT ON CLARO.VLAN_CFG
FOR EACH ROW
BEGIN
  IF :NEW.ID_VLAN_CFG IS NULL THEN
    SELECT CLARO.id_generator.NEXTVAL INTO :NEW.ID_VLAN_CFG FROM DUAL;
  END IF;
END;
/
