-- Trigger para populamento de Sequence | Tabela: MATRIX
CREATE OR REPLACE TRIGGER CLARO.TRG_BI_MATRIX
BEFORE INSERT ON CLARO.MATRIX
FOR EACH ROW
BEGIN
  IF :NEW.ID_MATRIX IS NULL THEN
    SELECT CLARO.MATRIX_ID_GEN.NEXTVAL INTO :NEW.ID_MATRIX FROM DUAL;
  END IF;
END;
/
