-- Trigger para populamento de Sequence | Tabela: SDH_MAPPING_DM800
CREATE OR REPLACE TRIGGER TRG_BI_SDH_MAPPING_DM800
BEFORE INSERT ON SDH_MAPPING_DM800
FOR EACH ROW
BEGIN
  IF :NEW.ID_SDH_MAPPING_DM800 IS NULL THEN
    SELECT sdh_mapping_dm800_gen.NEXTVAL INTO :NEW.ID_SDH_MAPPING_DM800 FROM DUAL;
  END IF;
END;
/
