-- Ordem: 001 | Tabela: CIRCUIT_END | Depth: 0
INSERT INTO CIRCUIT_END
(
CONFIG_TYPE,
NOVACOLUNA,
ERP_CODE
)
SELECT
src.CONFIG_TYPE,
src.NOVACOLUNA,
src.ID_CIRCUIT_END AS ERP_CODE
FROM CLARO.CIRCUIT_END src

WHERE NOT EXISTS (
    SELECT 1 FROM CIRCUIT_END dest WHERE dest.ERP_CODE = src.ID_CIRCUIT_END
);
COMMIT;