-- Ordem: 001 | Tabela: CIRCUIT_END | Depth: 0
INSERT INTO CLARO.CIRCUIT_END (
ID_CIRCUIT_END,
CONFIG_TYPE
)
SELECT 
src.ID_CIRCUIT_END,
src.CONFIG_TYPE
FROM OI.CIRCUIT_END src

WHERE NOT EXISTS (SELECT 1 FROM CLARO.CIRCUIT_END dest WHERE dest.ERP_CODE = TRIM(CAST(src.ID_CIRCUIT_END AS VARCHAR2(64))));
COMMIT;