-- Ordem: 002 | Tabela: CIRCUIT_EVENT | Depth: 0
INSERT INTO CIRCUIT_EVENT
(
CORR_ID,
EVENT_TIME,
EVENT_TYPE,
EVENT_VALUE,
DESCRIPTION,
SEVERITY,
EVENT_GROUP,
CLEARED,
ACK,
ACK_USER,
ACK_TIME,
CIRCUIT_ID,
CIRCUIT_NAME,
CIRCUIT_PRIO,
CIRCUIT_TYPE,
CIRCUIT_RATE,
CIRCUIT_PROTECTION,
CIRCUIT_A_END,
CIRCUIT_Z_END,
CIRCUIT_MANAGEMENT_LEVEL,
CUSTOMER_NAME,
CUSTOMER_PRIO,
SERVICE,
ACRONYM,
NOVACOLUNA,
ERP_CODE
)
SELECT
src.CORR_ID,
src.EVENT_TIME,
src.EVENT_TYPE,
src.EVENT_VALUE,
src.DESCRIPTION,
src.SEVERITY,
src.EVENT_GROUP,
src.CLEARED,
src.ACK,
src.ACK_USER,
src.ACK_TIME,
src.CIRCUIT_ID,
src.CIRCUIT_NAME,
src.CIRCUIT_PRIO,
src.CIRCUIT_TYPE,
src.CIRCUIT_RATE,
src.CIRCUIT_PROTECTION,
src.CIRCUIT_A_END,
src.CIRCUIT_Z_END,
src.CIRCUIT_MANAGEMENT_LEVEL,
src.CUSTOMER_NAME,
src.CUSTOMER_PRIO,
src.SERVICE,
src.ACRONYM,
src.NOVACOLUNA,
src.ID AS ERP_CODE
FROM CLARO.CIRCUIT_EVENT src

WHERE NOT EXISTS (
    SELECT 1 FROM CIRCUIT_EVENT dest WHERE dest.ERP_CODE = src.ID
);
COMMIT;