-- Ordem: 004 | Tabela: CIRCUIT_FILTER | Depth: 0
INSERT INTO CIRCUIT_FILTER
(
FILTER_NAME,
NOVACOLUNA,
ERP_CODE
)
SELECT
src.FILTER_NAME,
src.NOVACOLUNA,
src.FILTER_ID AS ERP_CODE
FROM CLARO.CIRCUIT_FILTER src

WHERE NOT EXISTS (
    SELECT 1 FROM CIRCUIT_FILTER dest WHERE dest.ERP_CODE = src.FILTER_ID
);
COMMIT;