-- Ordem: 004 | Tabela: CIRCUIT_FILTER | Depth: 0
INSERT INTO CLARO.CIRCUIT_FILTER (
FILTER_ID,
FILTER_NAME
)
SELECT 
src.FILTER_ID,
src.FILTER_NAME
FROM OI.CIRCUIT_FILTER src

WHERE NOT EXISTS (SELECT 1 FROM CLARO.CIRCUIT_FILTER dest WHERE dest.ERP_CODE = TRIM(CAST(src.FILTER_ID AS VARCHAR2(64))));
COMMIT;