-- Ordem: 005 | Tabela: CUSTOMER_PRIORITY | Depth: 0
INSERT INTO CLARO.CUSTOMER_PRIORITY (
PRIORITY,
LABEL,
ERP_CODE
)
SELECT 
src.PRIORITY,
src.LABEL,
TRIM(CAST(src.PRIORITY AS VARCHAR2(64))) AS ERP_CODE
FROM OI.CUSTOMER_PRIORITY src

WHERE NOT EXISTS (SELECT 1 FROM CLARO.CUSTOMER_PRIORITY dest WHERE dest.ERP_CODE = TRIM(CAST(src.PRIORITY AS VARCHAR2(64))));
