-- Ordem: 005 | Tabela: CUSTOMER_PRIORITY | Depth: 0
INSERT INTO CUSTOMER_PRIORITY
(
LABEL,
NOVACOLUNA,
ERP_CODE
)
SELECT
src.LABEL,
src.NOVACOLUNA,
src.PRIORITY AS ERP_CODE
FROM CLARO.CUSTOMER_PRIORITY src

WHERE NOT EXISTS (
    SELECT 1 FROM CUSTOMER_PRIORITY dest WHERE dest.ERP_CODE = src.PRIORITY
);
COMMIT;