-- Ordem: 006 | Tabela: PATH | Depth: 0
INSERT INTO CLARO.PATH (
ID_PATH,
ERP_CODE
)
SELECT 
src.ID_PATH,
TRIM(CAST(src.ID_PATH AS VARCHAR2(64))) AS ERP_CODE
FROM OI.PATH src

WHERE NOT EXISTS (SELECT 1 FROM CLARO.PATH dest WHERE dest.ERP_CODE = TRIM(CAST(src.ID_PATH AS VARCHAR2(64))));
