-- Ordem: 006 | Tabela: PATH | Depth: 0
INSERT INTO CLARO.PATH (
ID_PATH
)
SELECT 
src.ID_PATH
FROM OI.PATH src

WHERE NOT EXISTS (SELECT 1 FROM CLARO.PATH dest WHERE dest.ERP_CODE = TRIM(CAST(src.ID_PATH AS VARCHAR2(64))));
COMMIT;