-- Ordem: 007 | Tabela: PROVISIONING_RESOURCE | Depth: 0
INSERT INTO CLARO.PROVISIONING_RESOURCE (
RESOURCE_ID,
NAME,
STATUS,
SITUATION,
MGMT_LEVEL,
RESOURCE_TYPE
)
SELECT 
src.RESOURCE_ID,
src.NAME,
src.STATUS,
src.SITUATION,
src.MGMT_LEVEL,
src.RESOURCE_TYPE
FROM OI.PROVISIONING_RESOURCE src

WHERE NOT EXISTS (SELECT 1 FROM CLARO.PROVISIONING_RESOURCE dest WHERE dest.ERP_CODE = TRIM(CAST(src.RESOURCE_ID AS VARCHAR2(64))));
COMMIT;