-- Ordem: 008 | Tabela: SERVICE | Depth: 0
INSERT INTO CLARO.SERVICE (
ID,
NAME,
ACRONYM,
DESCRIPTION,
REQUIRES_MASK
)
SELECT 
src.ID,
src.NAME,
src.ACRONYM,
src.DESCRIPTION,
src.REQUIRES_MASK
FROM OI.SERVICE src

WHERE NOT EXISTS (SELECT 1 FROM CLARO.SERVICE dest WHERE dest.ERP_CODE = TRIM(CAST(src.ID AS VARCHAR2(64))));
COMMIT;