-- Ordem: 008 | Tabela: PATH | Depth: 0
INSERT INTO PATH
(
NOVACOLUNA,
ERP_CODE
)
SELECT
src.NOVACOLUNA,
src.ID_PATH AS ERP_CODE
FROM CLARO.PATH src

WHERE NOT EXISTS (
    SELECT 1 FROM PATH dest WHERE dest.ERP_CODE = src.ID_PATH
);
COMMIT;