-- Ordem: 009 | Tabela: SNMP | Depth: 0
INSERT INTO CLARO.SNMP (
ID,
HOSTNAME,
RETRIES,
TIMEOUT,
VERSION
)
SELECT 
src.ID,
src.HOSTNAME,
src.RETRIES,
src.TIMEOUT,
src.VERSION
FROM OI.SNMP src

WHERE NOT EXISTS (SELECT 1 FROM CLARO.SNMP dest WHERE dest.ERP_CODE = TRIM(CAST(src.ID AS VARCHAR2(64))));
COMMIT;