-- Ordem: 010 | Tabela: TB___OBJS_CUSTOM_LABEL__TB | Depth: 0
INSERT INTO CLARO.TB___OBJS_CUSTOM_LABEL__TB (
CL___PROXY_CODE__CL,
CL___MUX_NO__CL,
CL___MUX_LOCAL_ID__CL,
CL___OBJECT__CL,
CL___CUSTOM_LABEL__CL
)
SELECT 
src.CL___PROXY_CODE__CL,
src.CL___MUX_NO__CL,
src.CL___MUX_LOCAL_ID__CL,
src.CL___OBJECT__CL,
src.CL___CUSTOM_LABEL__CL
FROM OI.TB___OBJS_CUSTOM_LABEL__TB src

WHERE NOT EXISTS (SELECT 1 FROM CLARO.TB___OBJS_CUSTOM_LABEL__TB dest WHERE dest.ERP_CODE = LOWER(RAWTOHEX(STANDARD_HASH(TRIM(CAST(src.CL___PROXY_CODE__CL AS VARCHAR2(100))) || '|' || TRIM(CAST(src.CL___MUX_NO__CL AS VARCHAR2(100))) || '|' || TRIM(CAST(src.CL___MUX_LOCAL_ID__CL AS VARCHAR2(100))) || '|' || TRIM(CAST(src.CL___OBJECT__CL AS VARCHAR2(100))), 'MD5'))));
COMMIT;