-- Ordem: 010 | Tabela: PROVISIONING_RESOURCE | Depth: 0
INSERT INTO PROVISIONING_RESOURCE
(
NAME,
STATUS,
SITUATION,
MGMT_LEVEL,
RESOURCE_TYPE,
NOVACOLUNA,
ERP_CODE
)
SELECT
src.NAME,
src.STATUS,
src.SITUATION,
src.MGMT_LEVEL,
src.RESOURCE_TYPE,
src.NOVACOLUNA,
src.RESOURCE_ID AS ERP_CODE
FROM CLARO.PROVISIONING_RESOURCE src

WHERE NOT EXISTS (
    SELECT 1 FROM PROVISIONING_RESOURCE dest WHERE dest.ERP_CODE = src.RESOURCE_ID
);
COMMIT;