-- Ordem: 011 | Tabela: SERVICE | Depth: 0
INSERT INTO SERVICE
(
NAME,
ACRONYM,
DESCRIPTION,
REQUIRES_MASK,
NOVACOLUNA,
ERP_CODE
)
SELECT
src.NAME,
src.ACRONYM,
src.DESCRIPTION,
src.REQUIRES_MASK,
src.NOVACOLUNA,
src.ID AS ERP_CODE
FROM CLARO.SERVICE src

WHERE NOT EXISTS (
    SELECT 1 FROM SERVICE dest WHERE dest.ERP_CODE = src.ID
);
COMMIT;