-- Ordem: 011 | Tabela: TIME_SLOT | Depth: 0
INSERT INTO CLARO.TIME_SLOT (
ID,
TS_NUM
)
SELECT 
src.ID,
src.TS_NUM
FROM OI.TIME_SLOT src

WHERE NOT EXISTS (SELECT 1 FROM CLARO.TIME_SLOT dest WHERE dest.ERP_CODE = TRIM(CAST(src.ID AS VARCHAR2(64))));
COMMIT;