-- Ordem: 012 | Tabela: CIRCUIT_DEVICE_END | Depth: 1
INSERT INTO CLARO.CIRCUIT_DEVICE_END (
ID_CIRCUIT_END,
PROXY_CODE,
DEV_NO,
DEV_LOCAL_ID,
SNC_TYPE,
ERP_CODE
)
SELECT 
j68.ID_CIRCUIT_END AS ID_CIRCUIT_END,
src.PROXY_CODE,
src.DEV_NO,
src.DEV_LOCAL_ID,
src.SNC_TYPE,
TRIM(CAST(src.ID_CIRCUIT_END AS VARCHAR2(64))) AS ERP_CODE
FROM OI.CIRCUIT_DEVICE_END src
LEFT JOIN CLARO.CIRCUIT_END j68 ON j68.ERP_CODE = TRIM(CAST(src.ID_CIRCUIT_END AS VARCHAR2(64)))
WHERE NOT EXISTS (SELECT 1 FROM CLARO.CIRCUIT_DEVICE_END dest WHERE dest.ERP_CODE = TRIM(CAST(src.ID_CIRCUIT_END AS VARCHAR2(64))));
