-- Ordem: 013 | Tabela: CIRCUIT_FILTER_PROPERTY | Depth: 1
INSERT INTO CLARO.CIRCUIT_FILTER_PROPERTY (
FILTER_ID,
PROPERTY_NAME,
PROPERTY_VALUE,
ERP_CODE
)
SELECT 
j70.FILTER_ID AS FILTER_ID,
src.PROPERTY_NAME,
src.PROPERTY_VALUE,
LOWER(RAWTOHEX(STANDARD_HASH(TRIM(CAST(src.FILTER_ID AS VARCHAR2(100))) || '|' || TRIM(CAST(src.PROPERTY_NAME AS VARCHAR2(100))), 'MD5'))) AS ERP_CODE
FROM OI.CIRCUIT_FILTER_PROPERTY src
LEFT JOIN CLARO.CIRCUIT_FILTER j70 ON j70.ERP_CODE = TRIM(CAST(src.FILTER_ID AS VARCHAR2(64)))
WHERE NOT EXISTS (SELECT 1 FROM CLARO.CIRCUIT_FILTER_PROPERTY dest WHERE dest.ERP_CODE = LOWER(RAWTOHEX(STANDARD_HASH(TRIM(CAST(src.FILTER_ID AS VARCHAR2(100))) || '|' || TRIM(CAST(src.PROPERTY_NAME AS VARCHAR2(100))), 'MD5'))));
