-- Ordem: 014 | Tabela: CIRCUIT_PORT_END | Depth: 1
INSERT INTO CLARO.CIRCUIT_PORT_END (
ID_CIRCUIT_END,
PROXY_CODE,
DEV_NO,
DEV_LOCAL_ID,
SLOT_NO,
PORT_NO,
MODEL_CODE,
VLAN_ID_BUNDLE_PORT_NO,
USE_DS0
)
SELECT 
j76.ID_CIRCUIT_END AS ID_CIRCUIT_END,
src.PROXY_CODE,
src.DEV_NO,
src.DEV_LOCAL_ID,
src.SLOT_NO,
src.PORT_NO,
src.MODEL_CODE,
src.VLAN_ID_BUNDLE_PORT_NO,
src.USE_DS0
FROM OI.CIRCUIT_PORT_END src
LEFT JOIN CLARO.CIRCUIT_END j76 ON j76.ERP_CODE = TRIM(CAST(src.ID_CIRCUIT_END AS VARCHAR2(64)))
WHERE NOT EXISTS (SELECT 1 FROM CLARO.CIRCUIT_PORT_END dest WHERE dest.ERP_CODE = TRIM(CAST(src.ID_CIRCUIT_END AS VARCHAR2(64))));
COMMIT;