-- Ordem: 015 | Tabela: TB___OBJS_CUSTOM_LABEL__TB | Depth: 0
INSERT INTO TB___OBJS_CUSTOM_LABEL__TB
(
CL___PROXY_CODE__CL,
CL___MUX_NO__CL,
CL___OBJECT__CL,
CL___CUSTOM_LABEL__CL,
NOVACOLUNA,
ERP_CODE
)
SELECT
src.CL___PROXY_CODE__CL,
src.CL___MUX_NO__CL,
src.CL___OBJECT__CL,
src.CL___CUSTOM_LABEL__CL,
src.NOVACOLUNA,
src.CL___MUX_LOCAL_ID__CL AS ERP_CODE
FROM CLARO.TB___OBJS_CUSTOM_LABEL__TB src

WHERE NOT EXISTS (
    SELECT 1 FROM TB___OBJS_CUSTOM_LABEL__TB dest WHERE dest.ERP_CODE = src.CL___MUX_LOCAL_ID__CL
);
COMMIT;