-- Ordem: 015 | Tabela: CIRCUIT_PROTECTION | Depth: 1
INSERT INTO CLARO.CIRCUIT_PROTECTION (
ID_CIRCUIT_PROTECTION,
NAME,
ID_PATH,
ERP_CODE
)
SELECT 
src.ID_CIRCUIT_PROTECTION,
src.NAME,
j78.ID_PATH AS ID_PATH,
TRIM(CAST(src.ID_CIRCUIT_PROTECTION AS VARCHAR2(64))) AS ERP_CODE
FROM OI.CIRCUIT_PROTECTION src
LEFT JOIN CLARO.PATH j78 ON j78.ERP_CODE = TRIM(CAST(src.ID_PATH AS VARCHAR2(64)))
WHERE NOT EXISTS (SELECT 1 FROM CLARO.CIRCUIT_PROTECTION dest WHERE dest.ERP_CODE = TRIM(CAST(src.ID_CIRCUIT_PROTECTION AS VARCHAR2(64))));
