-- Ordem: 016 | Tabela: CUSTOMER | Depth: 1
INSERT INTO CLARO.CUSTOMER (
CUSTOMER_ID,
NAME,
ADDRESS,
CITY,
STATE,
COUNTRY,
AREA_CODE,
PHONE,
EMAIL,
CONTACT,
NOTES,
PRIORITY
)
SELECT 
src.CUSTOMER_ID,
src.NAME,
src.ADDRESS,
src.CITY,
src.STATE,
src.COUNTRY,
src.AREA_CODE,
src.PHONE,
src.EMAIL,
src.CONTACT,
src.NOTES,
j98.PRIORITY AS PRIORITY
FROM OI.CUSTOMER src
LEFT JOIN CLARO.CUSTOMER_PRIORITY j98 ON j98.ERP_CODE = TRIM(CAST(src.PRIORITY AS VARCHAR2(64)))
WHERE NOT EXISTS (SELECT 1 FROM CLARO.CUSTOMER dest WHERE dest.ERP_CODE = TRIM(CAST(src.CUSTOMER_ID AS VARCHAR2(64))));
COMMIT;