-- Ordem: 017 | Tabela: TIME_SLOT | Depth: 0
INSERT INTO TIME_SLOT
(
TS_NUM,
NOVACOLUNA,
ERP_CODE
)
SELECT
src.TS_NUM,
src.NOVACOLUNA,
src.ID AS ERP_CODE
FROM CLARO.TIME_SLOT src

WHERE NOT EXISTS (
    SELECT 1 FROM TIME_SLOT dest WHERE dest.ERP_CODE = src.ID
);
COMMIT;