-- Ordem: 017 | Tabela: GRAPHIC | Depth: 1
INSERT INTO CLARO.GRAPHIC (
GRAPHIC_ID,
GRAPHIC_PARENT
)
SELECT 
src.GRAPHIC_ID,
j140.GRAPHIC_ID AS GRAPHIC_PARENT
FROM OI.GRAPHIC src
LEFT JOIN CLARO.GRAPHIC j140 ON j140.ERP_CODE = TRIM(CAST(src.GRAPHIC_PARENT AS VARCHAR2(64)))
WHERE NOT EXISTS (SELECT 1 FROM CLARO.GRAPHIC dest WHERE dest.ERP_CODE = TRIM(CAST(src.GRAPHIC_ID AS VARCHAR2(64))));
COMMIT;