-- Ordem: 018 | Tabela: CIRCUIT_DEVICE_END | Depth: 1
INSERT INTO CIRCUIT_DEVICE_END
(
ID_CIRCUIT_END,
PROXY_CODE,
DEV_NO,
DEV_LOCAL_ID,
SNC_TYPE,
NOVACOLUNA,
ERP_CODE
)
SELECT
j1.ID AS ID_CIRCUIT_END,
src.PROXY_CODE,
src.DEV_NO,
src.DEV_LOCAL_ID,
src.SNC_TYPE,
src.NOVACOLUNA,
src.ID_CIRCUIT_END AS ERP_CODE
FROM CLARO.CIRCUIT_DEVICE_END src
LEFT JOIN CIRCUIT_END j1 ON j1.ERP_CODE = src.ID_CIRCUIT_END
WHERE NOT EXISTS (
    SELECT 1 FROM CIRCUIT_DEVICE_END dest WHERE dest.ERP_CODE = src.ID_CIRCUIT_END
);
COMMIT;