-- Ordem: 018 | Tabela: MANAGEMENT_VLAN | Depth: 1
INSERT INTO CLARO.MANAGEMENT_VLAN (
RESOURCE_ID,
RESOURCE_ID,
RESOURCE_ID,
VLAN_OR_MGMT_ETH,
IP_ADDRESS,
TDM_MANAGEMENT_VLAN
)
SELECT 
j159.RESOURCE_ID AS RESOURCE_ID,
j159.RESOURCE_ID AS RESOURCE_ID,
j159.RESOURCE_ID AS RESOURCE_ID,
src.VLAN_OR_MGMT_ETH,
src.IP_ADDRESS,
src.TDM_MANAGEMENT_VLAN
FROM OI.MANAGEMENT_VLAN src
LEFT JOIN CLARO.PROVISIONING_RESOURCE j159 ON j159.ERP_CODE = TRIM(CAST(src.RESOURCE_ID AS VARCHAR2(64)))
WHERE NOT EXISTS (SELECT 1 FROM CLARO.MANAGEMENT_VLAN dest WHERE dest.ERP_CODE = LOWER(RAWTOHEX(STANDARD_HASH(TRIM(CAST(src.RESOURCE_ID AS VARCHAR2(100))) || '|' || TRIM(CAST(src.VLAN_OR_MGMT_ETH AS VARCHAR2(100))), 'MD5'))));
COMMIT;