-- Ordem: 019 | Tabela: CIRCUIT_FILTER_PROPERTY | Depth: 1
INSERT INTO CIRCUIT_FILTER_PROPERTY
(
PROPERTY_NAME,
PROPERTY_VALUE,
NOVACOLUNA,
ERP_CODE
)
SELECT
src.PROPERTY_NAME,
src.PROPERTY_VALUE,
src.NOVACOLUNA,
src.FILTER_ID AS ERP_CODE
FROM CLARO.CIRCUIT_FILTER_PROPERTY src
LEFT JOIN CIRCUIT_FILTER j1 ON j1.ERP_CODE = src.FILTER_ID
WHERE NOT EXISTS (
    SELECT 1 FROM CIRCUIT_FILTER_PROPERTY dest WHERE dest.ERP_CODE = src.FILTER_ID
);
COMMIT;