-- Ordem: 019 | Tabela: PATH_SECTION | Depth: 1
INSERT INTO CLARO.PATH_SECTION (
ID_PATH_SECTION,
ID_PATH,
SECTION_ORDER,
ERP_CODE
)
SELECT 
src.ID_PATH_SECTION,
j219.ID_PATH AS ID_PATH,
src.SECTION_ORDER,
TRIM(CAST(src.ID_PATH_SECTION AS VARCHAR2(64))) AS ERP_CODE
FROM OI.PATH_SECTION src
LEFT JOIN CLARO.PATH j219 ON j219.ERP_CODE = TRIM(CAST(src.ID_PATH AS VARCHAR2(64)))
WHERE NOT EXISTS (SELECT 1 FROM CLARO.PATH_SECTION dest WHERE dest.ERP_CODE = TRIM(CAST(src.ID_PATH_SECTION AS VARCHAR2(64))));
