-- Ordem: 020 | Tabela: CIRCUIT_PORT_END | Depth: 1
INSERT INTO CIRCUIT_PORT_END
(
ID_CIRCUIT_END,
PROXY_CODE,
DEV_NO,
DEV_LOCAL_ID,
SLOT_NO,
PORT_NO,
MODEL_CODE,
VLAN_ID_BUNDLE_PORT_NO,
USE_DS0,
NOVACOLUNA,
ERP_CODE
)
SELECT
j1.ID AS ID_CIRCUIT_END,
src.PROXY_CODE,
src.DEV_NO,
src.DEV_LOCAL_ID,
src.SLOT_NO,
src.PORT_NO,
src.MODEL_CODE,
src.VLAN_ID_BUNDLE_PORT_NO,
src.USE_DS0,
src.NOVACOLUNA,
src.ID_CIRCUIT_END AS ERP_CODE
FROM CLARO.CIRCUIT_PORT_END src
LEFT JOIN CIRCUIT_END j1 ON j1.ERP_CODE = src.ID_CIRCUIT_END
WHERE NOT EXISTS (
    SELECT 1 FROM CIRCUIT_PORT_END dest WHERE dest.ERP_CODE = src.ID_CIRCUIT_END
);
COMMIT;