-- Ordem: 020 | Tabela: RESOURCE_ACTION | Depth: 1
INSERT INTO CLARO.RESOURCE_ACTION (
RESOURCE_ID,
ACTION_TYPE,
ACTION_DATE,
ACTION_USER,
ACTION_CLIENT,
ERP_CODE
)
SELECT 
j274.RESOURCE_ID AS RESOURCE_ID,
src.ACTION_TYPE,
src.ACTION_DATE,
src.ACTION_USER,
src.ACTION_CLIENT,
LOWER(RAWTOHEX(STANDARD_HASH(TRIM(CAST(src.RESOURCE_ID AS VARCHAR2(100))) || '|' || TRIM(CAST(src.ACTION_TYPE AS VARCHAR2(100))), 'MD5'))) AS ERP_CODE
FROM OI.RESOURCE_ACTION src
LEFT JOIN CLARO.PROVISIONING_RESOURCE j274 ON j274.ERP_CODE = TRIM(CAST(src.RESOURCE_ID AS VARCHAR2(64)))
WHERE NOT EXISTS (SELECT 1 FROM CLARO.RESOURCE_ACTION dest WHERE dest.ERP_CODE = LOWER(RAWTOHEX(STANDARD_HASH(TRIM(CAST(src.RESOURCE_ID AS VARCHAR2(100))) || '|' || TRIM(CAST(src.ACTION_TYPE AS VARCHAR2(100))), 'MD5'))));
