-- Ordem: 021 | Tabela: SNMPV1_2 | Depth: 1
INSERT INTO CLARO.SNMPV1_2 (
ID,
ID,
ID,
READ_COMMUNITY,
WRITE_COMMUNITY,
ERP_CODE
)
SELECT 
j344.ID AS ID,
j344.ID AS ID,
j344.ID AS ID,
src.READ_COMMUNITY,
src.WRITE_COMMUNITY,
TRIM(CAST(src.ID AS VARCHAR2(64))) AS ERP_CODE
FROM OI.SNMPV1_2 src
LEFT JOIN CLARO.SNMP j344 ON j344.ERP_CODE = TRIM(CAST(src.ID AS VARCHAR2(64)))
WHERE NOT EXISTS (SELECT 1 FROM CLARO.SNMPV1_2 dest WHERE dest.ERP_CODE = TRIM(CAST(src.ID AS VARCHAR2(64))));
