-- Ordem: 021 | Tabela: CIRCUIT_PROTECTION | Depth: 1
INSERT INTO CIRCUIT_PROTECTION
(
NAME,
ID_PATH,
NOVACOLUNA,
ERP_CODE
)
SELECT
src.NAME,
j3.ID AS ID_PATH,
src.NOVACOLUNA,
src.ID_CIRCUIT_PROTECTION AS ERP_CODE
FROM CLARO.CIRCUIT_PROTECTION src
LEFT JOIN PATH j3 ON j3.ERP_CODE = src.ID_PATH
WHERE NOT EXISTS (
    SELECT 1 FROM CIRCUIT_PROTECTION dest WHERE dest.ERP_CODE = src.ID_CIRCUIT_PROTECTION
);
COMMIT;