-- Ordem: 022 | Tabela: TB___PROXIES__TB | Depth: 1
INSERT INTO CLARO.TB___PROXIES__TB (
CL___PROXY_CODE__CL,
CL___MODEL_CODE__CL,
CL___PROXY_STATUS__CL,
CL___PROXY_HOSTNAME__CL,
CL___PROXY_AG_VS__CL,
CL___VENDOR_CODE__CL
)
SELECT 
src.CL___PROXY_CODE__CL,
j381.CL___MODEL_CODE__CL AS CL___MODEL_CODE__CL,
src.CL___PROXY_STATUS__CL,
src.CL___PROXY_HOSTNAME__CL,
src.CL___PROXY_AG_VS__CL,
src.CL___VENDOR_CODE__CL
FROM OI.TB___PROXIES__TB src
LEFT JOIN CLARO.TB___MODELS__TB j381 ON j381.CL___MODEL_CODE__CL = src.CL___MODEL_CODE__CL
WHERE NOT EXISTS (SELECT 1 FROM CLARO.TB___PROXIES__TB dest WHERE dest.ERP_CODE = TRIM(CAST(src.CL___PROXY_CODE__CL AS VARCHAR2(64))));
COMMIT;