-- Ordem: 022 | Tabela: CUSTOMER | Depth: 1
INSERT INTO CUSTOMER
(
NAME,
ADDRESS,
CITY,
STATE,
COUNTRY,
AREA_CODE,
PHONE,
EMAIL,
CONTACT,
NOTES,
PRIORITY,
NOVACOLUNA,
ERP_CODE
)
SELECT
src.NAME,
src.ADDRESS,
src.CITY,
src.STATE,
src.COUNTRY,
src.AREA_CODE,
src.PHONE,
src.EMAIL,
src.CONTACT,
src.NOTES,
j12.ID AS PRIORITY,
src.NOVACOLUNA,
src.CUSTOMER_ID AS ERP_CODE
FROM CLARO.CUSTOMER src
LEFT JOIN CUSTOMER_PRIORITY j12 ON j12.ERP_CODE = src.PRIORITY
WHERE NOT EXISTS (
    SELECT 1 FROM CUSTOMER dest WHERE dest.ERP_CODE = src.CUSTOMER_ID
);
COMMIT;