-- Ordem: 023 | Tabela: TIME_SLOT_MAPPING | Depth: 1
INSERT INTO CLARO.TIME_SLOT_MAPPING (
MAPPING_TYPE,
TS_SRC_ID,
TS_SRC_ID,
TS_SRC_ID,
TS_DST_ID,
TS_DST_ID,
TS_DST_ID
)
SELECT 
src.MAPPING_TYPE,
j407.ID AS TS_SRC_ID,
j407.ID AS TS_SRC_ID,
j407.ID AS TS_SRC_ID,
j406.ID AS TS_DST_ID,
j406.ID AS TS_DST_ID,
j406.ID AS TS_DST_ID
FROM OI.TIME_SLOT_MAPPING src
LEFT JOIN CLARO.TIME_SLOT j406 ON j406.ERP_CODE = TRIM(CAST(src.TS_DST_ID AS VARCHAR2(64)))
LEFT JOIN CLARO.TIME_SLOT j407 ON j407.ERP_CODE = TRIM(CAST(src.TS_SRC_ID AS VARCHAR2(64)))
WHERE NOT EXISTS (SELECT 1 FROM CLARO.TIME_SLOT_MAPPING dest WHERE dest.ERP_CODE = LOWER(RAWTOHEX(STANDARD_HASH(TRIM(CAST(src.TS_SRC_ID AS VARCHAR2(100))) || '|' || TRIM(CAST(src.TS_DST_ID AS VARCHAR2(100))), 'MD5'))));
COMMIT;