-- Ordem: 023 | Tabela: GRAPHIC | Depth: 1
INSERT INTO GRAPHIC
(
GRAPHIC_PARENT,
NOVACOLUNA,
ERP_CODE
)
SELECT
j2.ID AS GRAPHIC_PARENT,
src.NOVACOLUNA,
src.GRAPHIC_ID AS ERP_CODE
FROM CLARO.GRAPHIC src
LEFT JOIN GRAPHIC j2 ON j2.ERP_CODE = src.GRAPHIC_PARENT
WHERE NOT EXISTS (
    SELECT 1 FROM GRAPHIC dest WHERE dest.ERP_CODE = src.GRAPHIC_ID
);
COMMIT;