-- Ordem: 024 | Tabela: MANAGEMENT_VLAN | Depth: 1
INSERT INTO MANAGEMENT_VLAN
(
RESOURCE_ID,
VLAN_OR_MGMT_ETH,
IP_ADDRESS,
TDM_MANAGEMENT_VLAN,
NOVACOLUNA,
ERP_CODE
)
SELECT
j1.ID AS RESOURCE_ID,
src.VLAN_OR_MGMT_ETH,
src.IP_ADDRESS,
src.TDM_MANAGEMENT_VLAN,
src.NOVACOLUNA,
src.RESOURCE_ID AS ERP_CODE
FROM CLARO.MANAGEMENT_VLAN src
LEFT JOIN PROVISIONING_RESOURCE j1 ON j1.ERP_CODE = src.RESOURCE_ID
WHERE NOT EXISTS (
    SELECT 1 FROM MANAGEMENT_VLAN dest WHERE dest.ERP_CODE = src.RESOURCE_ID
);
COMMIT;