-- Ordem: 024 | Tabela: CIRCUIT | Depth: 2
INSERT INTO CLARO.CIRCUIT (
ID_CIRCUIT,
ID_CIRCUIT,
ID_CIRCUIT,
RATE,
CUSTOMER_ID,
CIRCUIT_TYPE,
PRIORITY,
ID_PROTECTION,
ID_PATH,
A_END,
Z_END,
DIRECTION,
CCAT,
SERVICE_ID,
SERVICE_ID,
SERVICE_ID
)
SELECT 
j57.RESOURCE_ID AS ID_CIRCUIT,
j57.RESOURCE_ID AS ID_CIRCUIT,
j57.RESOURCE_ID AS ID_CIRCUIT,
src.RATE,
j59.CUSTOMER_ID AS CUSTOMER_ID,
j62.ID_CIRCUIT_TYPE AS CIRCUIT_TYPE,
j63.PRIORITY AS PRIORITY,
j60.ID_CIRCUIT_PROTECTION AS ID_PROTECTION,
j61.ID_PATH AS ID_PATH,
j64.ID_CIRCUIT_END AS A_END,
j65.ID_CIRCUIT_END AS Z_END,
src.DIRECTION,
src.CCAT,
j58.ID AS SERVICE_ID,
j58.ID AS SERVICE_ID,
j58.ID AS SERVICE_ID
FROM OI.CIRCUIT src
LEFT JOIN CLARO.PROVISIONING_RESOURCE j57 ON j57.ERP_CODE = TRIM(CAST(src.ID_CIRCUIT AS VARCHAR2(64)))
LEFT JOIN CLARO.SERVICE j58 ON j58.ERP_CODE = TRIM(CAST(src.SERVICE_ID AS VARCHAR2(64)))
LEFT JOIN CLARO.CUSTOMER j59 ON j59.ERP_CODE = TRIM(CAST(src.CUSTOMER_ID AS VARCHAR2(64)))
LEFT JOIN CLARO.CIRCUIT_PROTECTION j60 ON j60.ERP_CODE = TRIM(CAST(src.ID_PROTECTION AS VARCHAR2(64)))
LEFT JOIN CLARO.PATH j61 ON j61.ERP_CODE = TRIM(CAST(src.ID_PATH AS VARCHAR2(64)))
LEFT JOIN CLARO.CIRCUIT_TYPE j62 ON j62.ID_CIRCUIT_TYPE = src.CIRCUIT_TYPE
LEFT JOIN CLARO.CIRCUIT_PRIORITY j63 ON j63.PRIORITY = src.PRIORITY
LEFT JOIN CLARO.CIRCUIT_END j64 ON j64.ERP_CODE = TRIM(CAST(src.A_END AS VARCHAR2(64)))
LEFT JOIN CLARO.CIRCUIT_END j65 ON j65.ERP_CODE = TRIM(CAST(src.Z_END AS VARCHAR2(64)))
WHERE NOT EXISTS (SELECT 1 FROM CLARO.CIRCUIT dest WHERE dest.ERP_CODE = TRIM(CAST(src.ID_CIRCUIT AS VARCHAR2(64))));
COMMIT;