-- Ordem: 025 | Tabela: CIRCUIT_DEVICE_END_PORT | Depth: 2
INSERT INTO CLARO.CIRCUIT_DEVICE_END_PORT (
ID_CIRCUIT_END,
SLOT_NO,
PORT_NO,
MODEL_CODE,
PORT_FUNCTION
)
SELECT 
j69.ID_CIRCUIT_END AS ID_CIRCUIT_END,
src.SLOT_NO,
src.PORT_NO,
src.MODEL_CODE,
src.PORT_FUNCTION
FROM OI.CIRCUIT_DEVICE_END_PORT src
LEFT JOIN CLARO.CIRCUIT_DEVICE_END j69 ON j69.ERP_CODE = TRIM(CAST(src.ID_CIRCUIT_END AS VARCHAR2(64)))
WHERE NOT EXISTS (SELECT 1 FROM CLARO.CIRCUIT_DEVICE_END_PORT dest WHERE dest.ERP_CODE = LOWER(RAWTOHEX(STANDARD_HASH(TRIM(CAST(src.ID_CIRCUIT_END AS VARCHAR2(100))) || '|' || TRIM(CAST(src.SLOT_NO AS VARCHAR2(100))) || '|' || TRIM(CAST(src.PORT_NO AS VARCHAR2(100))), 'MD5'))));
COMMIT;