-- Ordem: 025 | Tabela: PATH_SECTION | Depth: 1
INSERT INTO PATH_SECTION
(
ID_PATH,
SECTION_ORDER,
NOVACOLUNA,
ERP_CODE
)
SELECT
j2.ID AS ID_PATH,
src.SECTION_ORDER,
src.NOVACOLUNA,
src.ID_PATH_SECTION AS ERP_CODE
FROM CLARO.PATH_SECTION src
LEFT JOIN PATH j2 ON j2.ERP_CODE = src.ID_PATH
WHERE NOT EXISTS (
    SELECT 1 FROM PATH_SECTION dest WHERE dest.ERP_CODE = src.ID_PATH_SECTION
);
COMMIT;