-- Ordem: 026 | Tabela: CIRCUIT_PATH_SECTION | Depth: 2
INSERT INTO CLARO.CIRCUIT_PATH_SECTION (
ID_PATH_SECTION,
ID_CIRCUIT
)
SELECT 
j75.ID_PATH_SECTION AS ID_PATH_SECTION,
src.ID_CIRCUIT
FROM OI.CIRCUIT_PATH_SECTION src
LEFT JOIN CLARO.PATH_SECTION j75 ON j75.ERP_CODE = TRIM(CAST(src.ID_PATH_SECTION AS VARCHAR2(64)))
WHERE NOT EXISTS (SELECT 1 FROM CLARO.CIRCUIT_PATH_SECTION dest WHERE dest.ERP_CODE = LOWER(RAWTOHEX(STANDARD_HASH(TRIM(CAST(src.ID_PATH_SECTION AS VARCHAR2(100))) || '|' || TRIM(CAST(src.ID_CIRCUIT AS VARCHAR2(100))), 'MD5'))));
COMMIT;