-- Ordem: 026 | Tabela: RESOURCE_ACTION | Depth: 1
INSERT INTO RESOURCE_ACTION
(
RESOURCE_ID,
ACTION_DATE,
ACTION_USER,
ACTION_CLIENT,
NOVACOLUNA,
ERP_CODE
)
SELECT
j1.ID AS RESOURCE_ID,
src.ACTION_DATE,
src.ACTION_USER,
src.ACTION_CLIENT,
src.NOVACOLUNA,
src.ACTION_TYPE AS ERP_CODE
FROM CLARO.RESOURCE_ACTION src
LEFT JOIN PROVISIONING_RESOURCE j1 ON j1.ERP_CODE = src.RESOURCE_ID
WHERE NOT EXISTS (
    SELECT 1 FROM RESOURCE_ACTION dest WHERE dest.ERP_CODE = src.ACTION_TYPE
);
COMMIT;