-- Ordem: 027 | Tabela: CIRCUIT_PORT_END_TS | Depth: 2
INSERT INTO CLARO.CIRCUIT_PORT_END_TS (
ID_CIRCUIT_END,
TS_NO,
TS_ORDER,
ERP_CODE
)
SELECT 
j77.ID_CIRCUIT_END AS ID_CIRCUIT_END,
src.TS_NO,
src.TS_ORDER,
LOWER(RAWTOHEX(STANDARD_HASH(TRIM(CAST(src.ID_CIRCUIT_END AS VARCHAR2(100))) || '|' || TRIM(CAST(src.TS_NO AS VARCHAR2(100))), 'MD5'))) AS ERP_CODE
FROM OI.CIRCUIT_PORT_END_TS src
LEFT JOIN CLARO.CIRCUIT_PORT_END j77 ON j77.ERP_CODE = TRIM(CAST(src.ID_CIRCUIT_END AS VARCHAR2(64)))
WHERE NOT EXISTS (SELECT 1 FROM CLARO.CIRCUIT_PORT_END_TS dest WHERE dest.ERP_CODE = LOWER(RAWTOHEX(STANDARD_HASH(TRIM(CAST(src.ID_CIRCUIT_END AS VARCHAR2(100))) || '|' || TRIM(CAST(src.TS_NO AS VARCHAR2(100))), 'MD5'))));
