-- Ordem: 027 | Tabela: SNMPV1_2 | Depth: 1
INSERT INTO SNMPV1_2
(
READ_COMMUNITY,
WRITE_COMMUNITY,
NOVACOLUNA,
ERP_CODE
)
SELECT
src.READ_COMMUNITY,
src.WRITE_COMMUNITY,
src.NOVACOLUNA,
src.ID AS ERP_CODE
FROM CLARO.SNMPV1_2 src
LEFT JOIN SNMP j1 ON j1.ERP_CODE = src.ID
WHERE NOT EXISTS (
    SELECT 1 FROM SNMPV1_2 dest WHERE dest.ERP_CODE = src.ID
);
COMMIT;