-- Ordem: 028 | Tabela: CROSS_PATH_SECTION | Depth: 2
INSERT INTO CLARO.CROSS_PATH_SECTION (
ID_PATH_SECTION,
PROXY_CODE,
DEV_NO,
DEV_LOCAL_ID,
SLOT_SRC,
PORT_SRC,
TYPE_SRC,
SLOT_DST,
PORT_DST,
TYPE_DST,
ERP_CODE
)
SELECT 
j96.ID_PATH_SECTION AS ID_PATH_SECTION,
src.PROXY_CODE,
src.DEV_NO,
src.DEV_LOCAL_ID,
src.SLOT_SRC,
src.PORT_SRC,
src.TYPE_SRC,
src.SLOT_DST,
src.PORT_DST,
src.TYPE_DST,
TRIM(CAST(src.ID_PATH_SECTION AS VARCHAR2(64))) AS ERP_CODE
FROM OI.CROSS_PATH_SECTION src
LEFT JOIN CLARO.PATH_SECTION j96 ON j96.ERP_CODE = TRIM(CAST(src.ID_PATH_SECTION AS VARCHAR2(64)))
WHERE NOT EXISTS (SELECT 1 FROM CLARO.CROSS_PATH_SECTION dest WHERE dest.ERP_CODE = TRIM(CAST(src.ID_PATH_SECTION AS VARCHAR2(64))));
