-- Ordem: 028 | Tabela: TB___PROXIES__TB | Depth: 1
INSERT INTO TB___PROXIES__TB
(
CL___MODEL_CODE__CL,
CL___PROXY_STATUS__CL,
CL___PROXY_HOSTNAME__CL,
CL___PROXY_AG_VS__CL,
CL___VENDOR_CODE__CL,
NOVACOLUNA,
ERP_CODE
)
SELECT
j2.ID AS CL___MODEL_CODE__CL,
src.CL___PROXY_STATUS__CL,
src.CL___PROXY_HOSTNAME__CL,
src.CL___PROXY_AG_VS__CL,
src.CL___VENDOR_CODE__CL,
src.NOVACOLUNA,
src.CL___PROXY_CODE__CL AS ERP_CODE
FROM CLARO.TB___PROXIES__TB src
LEFT JOIN TB___MODELS__TB j2 ON j2.ID = src.CL___MODEL_CODE__CL
WHERE NOT EXISTS (
    SELECT 1 FROM TB___PROXIES__TB dest WHERE dest.ERP_CODE = src.CL___PROXY_CODE__CL
);
COMMIT;