-- Ordem: 029 | Tabela: TIME_SLOT_MAPPING | Depth: 1
INSERT INTO TIME_SLOT_MAPPING
(
MAPPING_TYPE,
TS_SRC_ID,
TS_DST_ID,
NOVACOLUNA,
ERP_CODE
)
SELECT
src.MAPPING_TYPE,
j2.ID AS TS_SRC_ID,
j3.ID AS TS_DST_ID,
src.NOVACOLUNA,
src.TS_DST_ID AS ERP_CODE
FROM CLARO.TIME_SLOT_MAPPING src
LEFT JOIN TIME_SLOT j2 ON j2.ERP_CODE = src.TS_SRC_ID
LEFT JOIN TIME_SLOT j3 ON j3.ERP_CODE = src.TS_DST_ID
WHERE NOT EXISTS (
    SELECT 1 FROM TIME_SLOT_MAPPING dest WHERE dest.ERP_CODE = src.TS_DST_ID
);
COMMIT;