-- Ordem: 030 | Tabela: CIRCUIT | Depth: 2
INSERT INTO CIRCUIT
(
ID_CIRCUIT,
RATE,
CUSTOMER_ID,
CIRCUIT_TYPE,
PRIORITY,
ID_PROTECTION,
ID_PATH,
A_END,
Z_END,
DIRECTION,
CCAT,
SERVICE_ID,
NOVACOLUNA,
ERP_CODE
)
SELECT
j1.ID AS ID_CIRCUIT,
src.RATE,
j3.ID AS CUSTOMER_ID,
j4.ID AS CIRCUIT_TYPE,
j5.ID AS PRIORITY,
j6.ID AS ID_PROTECTION,
j7.ID AS ID_PATH,
j8.ID AS A_END,
j9.ID AS Z_END,
src.DIRECTION,
src.CCAT,
j12.ID AS SERVICE_ID,
src.NOVACOLUNA,
src.ID_CIRCUIT AS ERP_CODE
FROM CLARO.CIRCUIT src
LEFT JOIN PROVISIONING_RESOURCE j1 ON j1.ERP_CODE = src.ID_CIRCUIT
LEFT JOIN CUSTOMER j3 ON j3.ERP_CODE = src.CUSTOMER_ID
LEFT JOIN CIRCUIT_TYPE j4 ON j4.ID = src.CIRCUIT_TYPE
LEFT JOIN CIRCUIT_PRIORITY j5 ON j5.ID = src.PRIORITY
LEFT JOIN CIRCUIT_PROTECTION j6 ON j6.ERP_CODE = src.ID_PROTECTION
LEFT JOIN PATH j7 ON j7.ERP_CODE = src.ID_PATH
LEFT JOIN CIRCUIT_END j8 ON j8.ERP_CODE = src.A_END
LEFT JOIN CIRCUIT_END j9 ON j9.ERP_CODE = src.Z_END
LEFT JOIN SERVICE j12 ON j12.ERP_CODE = src.SERVICE_ID
WHERE NOT EXISTS (
    SELECT 1 FROM CIRCUIT dest WHERE dest.ERP_CODE = src.ID_CIRCUIT
);
COMMIT;