-- Ordem: 030 | Tabela: MATRIX_MAPPING_PATH_SECTION | Depth: 2
INSERT INTO CLARO.MATRIX_MAPPING_PATH_SECTION (
ID_PATH_SECTION,
PROXY_CODE,
DEV_NO,
DEV_LOCAL_ID,
CONNECTION_SLOT,
CONNECTION_PORT,
MATRIX_SLOT,
MATRIX_PORT,
ERP_CODE
)
SELECT 
j168.ID_PATH_SECTION AS ID_PATH_SECTION,
src.PROXY_CODE,
src.DEV_NO,
src.DEV_LOCAL_ID,
src.CONNECTION_SLOT,
src.CONNECTION_PORT,
src.MATRIX_SLOT,
src.MATRIX_PORT,
TRIM(CAST(src.ID_PATH_SECTION AS VARCHAR2(64))) AS ERP_CODE
FROM OI.MATRIX_MAPPING_PATH_SECTION src
LEFT JOIN CLARO.PATH_SECTION j168 ON j168.ERP_CODE = TRIM(CAST(src.ID_PATH_SECTION AS VARCHAR2(64)))
WHERE NOT EXISTS (SELECT 1 FROM CLARO.MATRIX_MAPPING_PATH_SECTION dest WHERE dest.ERP_CODE = TRIM(CAST(src.ID_PATH_SECTION AS VARCHAR2(64))));
