-- Ordem: 031 | Tabela: NODE | Depth: 2
INSERT INTO CLARO.NODE (
GRAPHIC_ID,
NODE_ICON,
NODE_X,
NODE_Y
)
SELECT 
j196.GRAPHIC_ID AS GRAPHIC_ID,
src.NODE_ICON,
src.NODE_X,
src.NODE_Y
FROM OI.NODE src
LEFT JOIN CLARO.GRAPHIC j196 ON j196.ERP_CODE = TRIM(CAST(src.GRAPHIC_ID AS VARCHAR2(64)))
WHERE NOT EXISTS (SELECT 1 FROM CLARO.NODE dest WHERE dest.ERP_CODE = TRIM(CAST(src.GRAPHIC_ID AS VARCHAR2(64))));
COMMIT;