-- Ordem: 031 | Tabela: CIRCUIT_DEVICE_END_PORT | Depth: 2
INSERT INTO CIRCUIT_DEVICE_END_PORT
(
ID_CIRCUIT_END,
SLOT_NO,
PORT_NO,
MODEL_CODE,
PORT_FUNCTION,
NOVACOLUNA,
ERP_CODE
)
SELECT
j1.ID AS ID_CIRCUIT_END,
src.SLOT_NO,
src.PORT_NO,
src.MODEL_CODE,
src.PORT_FUNCTION,
src.NOVACOLUNA,
src.ID_CIRCUIT_END AS ERP_CODE
FROM CLARO.CIRCUIT_DEVICE_END_PORT src
LEFT JOIN CIRCUIT_DEVICE_END j1 ON j1.ERP_CODE = src.ID_CIRCUIT_END
WHERE NOT EXISTS (
    SELECT 1 FROM CIRCUIT_DEVICE_END_PORT dest WHERE dest.ERP_CODE = src.ID_CIRCUIT_END
);
COMMIT;