-- Ordem: 032 | Tabela: CIRCUIT_PATH_SECTION | Depth: 2
INSERT INTO CIRCUIT_PATH_SECTION
(
ID_PATH_SECTION,
NOVACOLUNA,
ERP_CODE
)
SELECT
j1.ID AS ID_PATH_SECTION,
src.NOVACOLUNA,
src.ID_CIRCUIT AS ERP_CODE
FROM CLARO.CIRCUIT_PATH_SECTION src
LEFT JOIN PATH_SECTION j1 ON j1.ERP_CODE = src.ID_PATH_SECTION
WHERE NOT EXISTS (
    SELECT 1 FROM CIRCUIT_PATH_SECTION dest WHERE dest.ERP_CODE = src.ID_CIRCUIT
);
COMMIT;