-- Ordem: 032 | Tabela: PORT_PATH_SECTION | Depth: 2
INSERT INTO CLARO.PORT_PATH_SECTION (
ID_PATH_SECTION,
PROXY_CODE,
DEV_NO,
DEV_LOCAL_ID,
SLOT_NO,
PORT_NO,
MODEL_CODE,
USE_STATUS,
ERP_CODE
)
SELECT 
j247.ID_PATH_SECTION AS ID_PATH_SECTION,
src.PROXY_CODE,
src.DEV_NO,
src.DEV_LOCAL_ID,
src.SLOT_NO,
src.PORT_NO,
src.MODEL_CODE,
src.USE_STATUS,
TRIM(CAST(src.ID_PATH_SECTION AS VARCHAR2(64))) AS ERP_CODE
FROM OI.PORT_PATH_SECTION src
LEFT JOIN CLARO.PATH_SECTION j247 ON j247.ERP_CODE = TRIM(CAST(src.ID_PATH_SECTION AS VARCHAR2(64)))
WHERE NOT EXISTS (SELECT 1 FROM CLARO.PORT_PATH_SECTION dest WHERE dest.ERP_CODE = TRIM(CAST(src.ID_PATH_SECTION AS VARCHAR2(64))));
