-- Ordem: 033 | Tabela: SDH_MAPPING_DM800_PATH_SECTION | Depth: 2
INSERT INTO CLARO.SDH_MAPPING_DM800_PATH_SECTION (
ID_PATH_SECTION,
PROXY_CODE,
DEV_NO,
DEV_LOCAL_ID,
MAPPING_TYPE,
SLOT_SRC,
PORT_SRC,
SLOT_DST,
PORT_DST,
SLOT_SRC_PROT,
PORT_SRC_PROT,
SLOT_DST_PROT,
PORT_DST_PROT,
ERP_CODE
)
SELECT 
j325.ID_PATH_SECTION AS ID_PATH_SECTION,
src.PROXY_CODE,
src.DEV_NO,
src.DEV_LOCAL_ID,
src.MAPPING_TYPE,
src.SLOT_SRC,
src.PORT_SRC,
src.SLOT_DST,
src.PORT_DST,
src.SLOT_SRC_PROT,
src.PORT_SRC_PROT,
src.SLOT_DST_PROT,
src.PORT_DST_PROT,
TRIM(CAST(src.ID_PATH_SECTION AS VARCHAR2(64))) AS ERP_CODE
FROM OI.SDH_MAPPING_DM800_PATH_SECTION src
LEFT JOIN CLARO.PATH_SECTION j325 ON j325.ERP_CODE = TRIM(CAST(src.ID_PATH_SECTION AS VARCHAR2(64)))
WHERE NOT EXISTS (SELECT 1 FROM CLARO.SDH_MAPPING_DM800_PATH_SECTION dest WHERE dest.ERP_CODE = TRIM(CAST(src.ID_PATH_SECTION AS VARCHAR2(64))));
