-- Ordem: 033 | Tabela: CIRCUIT_PORT_END_TS | Depth: 2
INSERT INTO CIRCUIT_PORT_END_TS
(
TS_NO,
TS_ORDER,
NOVACOLUNA,
ERP_CODE
)
SELECT
src.TS_NO,
src.TS_ORDER,
src.NOVACOLUNA,
src.ID_CIRCUIT_END AS ERP_CODE
FROM CLARO.CIRCUIT_PORT_END_TS src
LEFT JOIN CIRCUIT_PORT_END j1 ON j1.ERP_CODE = src.ID_CIRCUIT_END
WHERE NOT EXISTS (
    SELECT 1 FROM CIRCUIT_PORT_END_TS dest WHERE dest.ERP_CODE = src.ID_CIRCUIT_END
);
COMMIT;