-- Ordem: 034 | Tabela: SDH_MAPPING_PATH_SECTION | Depth: 2
INSERT INTO CLARO.SDH_MAPPING_PATH_SECTION (
ID_PATH_SECTION,
PROXY_CODE,
DEV_NO,
DEV_LOCAL_ID,
SLOT_SRC,
PORT_SRC,
SLOT_DST,
PORT_DST,
PROT_TYPE
)
SELECT 
j326.ID_PATH_SECTION AS ID_PATH_SECTION,
src.PROXY_CODE,
src.DEV_NO,
src.DEV_LOCAL_ID,
src.SLOT_SRC,
src.PORT_SRC,
src.SLOT_DST,
src.PORT_DST,
src.PROT_TYPE
FROM OI.SDH_MAPPING_PATH_SECTION src
LEFT JOIN CLARO.PATH_SECTION j326 ON j326.ERP_CODE = TRIM(CAST(src.ID_PATH_SECTION AS VARCHAR2(64)))
WHERE NOT EXISTS (SELECT 1 FROM CLARO.SDH_MAPPING_PATH_SECTION dest WHERE dest.ERP_CODE = TRIM(CAST(src.ID_PATH_SECTION AS VARCHAR2(64))));
COMMIT;