-- Ordem: 035 | Tabela: CUSTOM_MAPPING_PATH_SECTION | Depth: 2
INSERT INTO CUSTOM_MAPPING_PATH_SECTION
(
PROXY_CODE,
DEV_NO,
DEV_LOCAL_ID,
MAPPING_TYPE,
SLOT_SRC,
PORT_SRC,
SLOT_DST,
PORT_DST,
SLOT_SRC_PROT,
PORT_SRC_PROT,
SLOT_DST_PROT,
PORT_DST_PROT,
NOVACOLUNA,
ERP_CODE
)
SELECT
src.PROXY_CODE,
src.DEV_NO,
src.DEV_LOCAL_ID,
src.MAPPING_TYPE,
src.SLOT_SRC,
src.PORT_SRC,
src.SLOT_DST,
src.PORT_DST,
src.SLOT_SRC_PROT,
src.PORT_SRC_PROT,
src.SLOT_DST_PROT,
src.PORT_DST_PROT,
src.NOVACOLUNA,
src.ID_PATH_SECTION AS ERP_CODE
FROM CLARO.CUSTOM_MAPPING_PATH_SECTION src
LEFT JOIN PATH_SECTION j1 ON j1.ERP_CODE = src.ID_PATH_SECTION
WHERE NOT EXISTS (
    SELECT 1 FROM CUSTOM_MAPPING_PATH_SECTION dest WHERE dest.ERP_CODE = src.ID_PATH_SECTION
);
COMMIT;