-- Ordem: 036 | Tabela: VCG_MAPPING_PATH_SECTION | Depth: 2
INSERT INTO CLARO.VCG_MAPPING_PATH_SECTION (
ID_PATH_SECTION,
PROXY_CODE,
DEV_NO,
DEV_LOCAL_ID,
SLOT_NO,
PORT_NO,
TX_PORT_NO,
TX_SQN,
RX_PORT_NO,
RX_SQN,
SQM_ALARM
)
SELECT 
j413.ID_PATH_SECTION AS ID_PATH_SECTION,
src.PROXY_CODE,
src.DEV_NO,
src.DEV_LOCAL_ID,
src.SLOT_NO,
src.PORT_NO,
src.TX_PORT_NO,
src.TX_SQN,
src.RX_PORT_NO,
src.RX_SQN,
src.SQM_ALARM
FROM OI.VCG_MAPPING_PATH_SECTION src
LEFT JOIN CLARO.PATH_SECTION j413 ON j413.ERP_CODE = TRIM(CAST(src.ID_PATH_SECTION AS VARCHAR2(64)))
WHERE NOT EXISTS (SELECT 1 FROM CLARO.VCG_MAPPING_PATH_SECTION dest WHERE dest.ERP_CODE = TRIM(CAST(src.ID_PATH_SECTION AS VARCHAR2(64))));
COMMIT;