-- Ordem: 036 | Tabela: MATRIX_MAPPING_PATH_SECTION | Depth: 2
INSERT INTO MATRIX_MAPPING_PATH_SECTION
(
PROXY_CODE,
DEV_NO,
DEV_LOCAL_ID,
CONNECTION_SLOT,
CONNECTION_PORT,
MATRIX_SLOT,
MATRIX_PORT,
NOVACOLUNA,
ERP_CODE
)
SELECT
src.PROXY_CODE,
src.DEV_NO,
src.DEV_LOCAL_ID,
src.CONNECTION_SLOT,
src.CONNECTION_PORT,
src.MATRIX_SLOT,
src.MATRIX_PORT,
src.NOVACOLUNA,
src.ID_PATH_SECTION AS ERP_CODE
FROM CLARO.MATRIX_MAPPING_PATH_SECTION src
LEFT JOIN PATH_SECTION j1 ON j1.ERP_CODE = src.ID_PATH_SECTION
WHERE NOT EXISTS (
    SELECT 1 FROM MATRIX_MAPPING_PATH_SECTION dest WHERE dest.ERP_CODE = src.ID_PATH_SECTION
);
COMMIT;