-- Ordem: 037 | Tabela: NODE | Depth: 2
INSERT INTO NODE
(
NODE_ICON,
NODE_X,
NODE_Y,
NOVACOLUNA,
ERP_CODE
)
SELECT
src.NODE_ICON,
src.NODE_X,
src.NODE_Y,
src.NOVACOLUNA,
src.GRAPHIC_ID AS ERP_CODE
FROM CLARO.NODE src
LEFT JOIN GRAPHIC j1 ON j1.ERP_CODE = src.GRAPHIC_ID
WHERE NOT EXISTS (
    SELECT 1 FROM NODE dest WHERE dest.ERP_CODE = src.GRAPHIC_ID
);
COMMIT;