-- Ordem: 037 | Tabela: CIRCUIT_COMMENT | Depth: 3
INSERT INTO CLARO.CIRCUIT_COMMENT (
ID_CIRCUIT,
ID_COMMENT,
COMMENT_VALUE,
ERP_CODE
)
SELECT 
j66.ID_CIRCUIT AS ID_CIRCUIT,
j67.ID_COMMENT AS ID_COMMENT,
src.COMMENT_VALUE,
LOWER(RAWTOHEX(STANDARD_HASH(TRIM(CAST(src.ID_CIRCUIT AS VARCHAR2(100))) || '|' || TRIM(CAST(src.ID_COMMENT AS VARCHAR2(100))), 'MD5'))) AS ERP_CODE
FROM OI.CIRCUIT_COMMENT src
LEFT JOIN CLARO.CIRCUIT j66 ON j66.ERP_CODE = TRIM(CAST(src.ID_CIRCUIT AS VARCHAR2(64)))
LEFT JOIN CLARO.COMMENT_LABEL j67 ON j67.ID_COMMENT = src.ID_COMMENT
WHERE NOT EXISTS (SELECT 1 FROM CLARO.CIRCUIT_COMMENT dest WHERE dest.ERP_CODE = LOWER(RAWTOHEX(STANDARD_HASH(TRIM(CAST(src.ID_CIRCUIT AS VARCHAR2(100))) || '|' || TRIM(CAST(src.ID_COMMENT AS VARCHAR2(100))), 'MD5'))));
