-- Ordem: 038 | Tabela: PORT_PATH_SECTION | Depth: 2
INSERT INTO PORT_PATH_SECTION
(
ID_PATH_SECTION,
PROXY_CODE,
DEV_NO,
DEV_LOCAL_ID,
SLOT_NO,
PORT_NO,
MODEL_CODE,
USE_STATUS,
NOVACOLUNA,
ERP_CODE
)
SELECT
j1.ID AS ID_PATH_SECTION,
src.PROXY_CODE,
src.DEV_NO,
src.DEV_LOCAL_ID,
src.SLOT_NO,
src.PORT_NO,
src.MODEL_CODE,
src.USE_STATUS,
src.NOVACOLUNA,
src.ID_PATH_SECTION AS ERP_CODE
FROM CLARO.PORT_PATH_SECTION src
LEFT JOIN PATH_SECTION j1 ON j1.ERP_CODE = src.ID_PATH_SECTION
WHERE NOT EXISTS (
    SELECT 1 FROM PORT_PATH_SECTION dest WHERE dest.ERP_CODE = src.ID_PATH_SECTION
);
COMMIT;