-- Ordem: 038 | Tabela: CIRCUIT_OBJECT | Depth: 3
INSERT INTO CLARO.CIRCUIT_OBJECT (
ID_CIRCUIT,
OBJECT,
OBJ_INSTANCE,
OBJ_VALUE
)
SELECT 
j74.ID_CIRCUIT AS ID_CIRCUIT,
src.OBJECT,
src.OBJ_INSTANCE,
src.OBJ_VALUE
FROM OI.CIRCUIT_OBJECT src
LEFT JOIN CLARO.CIRCUIT j74 ON j74.ERP_CODE = TRIM(CAST(src.ID_CIRCUIT AS VARCHAR2(64)))
WHERE NOT EXISTS (SELECT 1 FROM CLARO.CIRCUIT_OBJECT dest WHERE dest.ERP_CODE = LOWER(RAWTOHEX(STANDARD_HASH(TRIM(CAST(src.ID_CIRCUIT AS VARCHAR2(100))) || '|' || TRIM(CAST(src.OBJECT AS VARCHAR2(100))) || '|' || TRIM(CAST(src.OBJ_INSTANCE AS VARCHAR2(100))), 'MD5'))));
COMMIT;