-- Ordem: 039 | Tabela: CIRCUIT_SITUATION_BY_DEVICE | Depth: 3
INSERT INTO CLARO.CIRCUIT_SITUATION_BY_DEVICE (
ID_CIRCUIT,
PROXY_CODE,
DEV_NO,
DEV_LOCAL_ID,
SITUATION
)
SELECT 
j80.ID_CIRCUIT AS ID_CIRCUIT,
src.PROXY_CODE,
src.DEV_NO,
src.DEV_LOCAL_ID,
src.SITUATION
FROM OI.CIRCUIT_SITUATION_BY_DEVICE src
LEFT JOIN CLARO.CIRCUIT j80 ON j80.ERP_CODE = TRIM(CAST(src.ID_CIRCUIT AS VARCHAR2(64)))
WHERE NOT EXISTS (SELECT 1 FROM CLARO.CIRCUIT_SITUATION_BY_DEVICE dest WHERE dest.ERP_CODE = LOWER(RAWTOHEX(STANDARD_HASH(TRIM(CAST(src.ID_CIRCUIT AS VARCHAR2(100))) || '|' || TRIM(CAST(src.PROXY_CODE AS VARCHAR2(100))) || '|' || TRIM(CAST(src.DEV_NO AS VARCHAR2(100))) || '|' || TRIM(CAST(src.DEV_LOCAL_ID AS VARCHAR2(100))), 'MD5'))));
COMMIT;