-- Ordem: 040 | Tabela: SDH_MAPPING_PATH_SECTION | Depth: 2
INSERT INTO SDH_MAPPING_PATH_SECTION
(
PROXY_CODE,
DEV_NO,
DEV_LOCAL_ID,
SLOT_SRC,
PORT_SRC,
SLOT_DST,
PORT_DST,
PROT_TYPE,
NOVACOLUNA,
ERP_CODE
)
SELECT
src.PROXY_CODE,
src.DEV_NO,
src.DEV_LOCAL_ID,
src.SLOT_SRC,
src.PORT_SRC,
src.SLOT_DST,
src.PORT_DST,
src.PROT_TYPE,
src.NOVACOLUNA,
src.ID_PATH_SECTION AS ERP_CODE
FROM CLARO.SDH_MAPPING_PATH_SECTION src
LEFT JOIN PATH_SECTION j1 ON j1.ERP_CODE = src.ID_PATH_SECTION
WHERE NOT EXISTS (
    SELECT 1 FROM SDH_MAPPING_PATH_SECTION dest WHERE dest.ERP_CODE = src.ID_PATH_SECTION
);
COMMIT;