-- Ordem: 040 | Tabela: CONNECTION | Depth: 3
INSERT INTO CLARO.CONNECTION (
GRAPHIC_ID,
CONNECTION_A_END_NODE,
CONNECTION_Z_END_NODE,
CONNECTION_STATUS
)
SELECT 
j90.GRAPHIC_ID AS GRAPHIC_ID,
j88.GRAPHIC_ID AS CONNECTION_A_END_NODE,
j89.GRAPHIC_ID AS CONNECTION_Z_END_NODE,
src.CONNECTION_STATUS
FROM OI.CONNECTION src
LEFT JOIN CLARO.NODE j88 ON j88.ERP_CODE = TRIM(CAST(src.CONNECTION_A_END_NODE AS VARCHAR2(64)))
LEFT JOIN CLARO.NODE j89 ON j89.ERP_CODE = TRIM(CAST(src.CONNECTION_Z_END_NODE AS VARCHAR2(64)))
LEFT JOIN CLARO.GRAPHIC j90 ON j90.ERP_CODE = TRIM(CAST(src.GRAPHIC_ID AS VARCHAR2(64)))
WHERE NOT EXISTS (SELECT 1 FROM CLARO.CONNECTION dest WHERE dest.ERP_CODE = TRIM(CAST(src.GRAPHIC_ID AS VARCHAR2(64))));
COMMIT;