-- Ordem: 041 | Tabela: CROSS_PATH_SECTION_TS | Depth: 3
INSERT INTO CLARO.CROSS_PATH_SECTION_TS (
ID_PATH_SECTION,
TS_SRC,
TS_DST,
ERP_CODE
)
SELECT 
j97.ID_PATH_SECTION AS ID_PATH_SECTION,
src.TS_SRC,
src.TS_DST,
LOWER(RAWTOHEX(STANDARD_HASH(TRIM(CAST(src.ID_PATH_SECTION AS VARCHAR2(100))) || '|' || TRIM(CAST(src.TS_SRC AS VARCHAR2(100))) || '|' || TRIM(CAST(src.TS_DST AS VARCHAR2(100))), 'MD5'))) AS ERP_CODE
FROM OI.CROSS_PATH_SECTION_TS src
LEFT JOIN CLARO.CROSS_PATH_SECTION j97 ON j97.ERP_CODE = TRIM(CAST(src.ID_PATH_SECTION AS VARCHAR2(64)))
WHERE NOT EXISTS (SELECT 1 FROM CLARO.CROSS_PATH_SECTION_TS dest WHERE dest.ERP_CODE = LOWER(RAWTOHEX(STANDARD_HASH(TRIM(CAST(src.ID_PATH_SECTION AS VARCHAR2(100))) || '|' || TRIM(CAST(src.TS_SRC AS VARCHAR2(100))) || '|' || TRIM(CAST(src.TS_DST AS VARCHAR2(100))), 'MD5'))));
