-- Ordem: 041 | Tabela: TB___MUXS__TB | Depth: 2
INSERT INTO TB___MUXS__TB
(
CL___PROXY_CODE__CL,
CL___MUX_NO__CL,
CL___MUX_SERIAL_NO__CL,
CL___MODEL_CODE__CL,
CL___MUX_FIRM_VERSION__CL,
CL___MUX_CPU_STATUS__CL,
CL___MUX_STATUS__CL,
CL___MUX_RESETS__CL,
CL___HARDWARE_ID__CL,
CL___STATUS_ID__CL,
CL___CONFIG_ID__CL,
CL___LAST_UPDATE__CL,
CL___VENDOR_CODE__CL,
CL___CIRCUIT_MISMATCH__CL,
NAME,
COUNTRY,
STATE,
CITY,
ROOM,
SHELF,
NOTES,
STATION,
HW_VERSION,
MANAGEABLE,
LAST_FAIL,
RESOURCE_ID,
LAST_FAIL_CAUSE,
PROJECT_ID,
ADDRESS,
MODEL_NAME,
NOVACOLUNA,
ERP_CODE
)
SELECT
j1.ID AS CL___PROXY_CODE__CL,
src.CL___MUX_NO__CL,
src.CL___MUX_SERIAL_NO__CL,
j5.ID AS CL___MODEL_CODE__CL,
src.CL___MUX_FIRM_VERSION__CL,
src.CL___MUX_CPU_STATUS__CL,
src.CL___MUX_STATUS__CL,
src.CL___MUX_RESETS__CL,
src.CL___HARDWARE_ID__CL,
src.CL___STATUS_ID__CL,
src.CL___CONFIG_ID__CL,
src.CL___LAST_UPDATE__CL,
j14.ID AS CL___VENDOR_CODE__CL,
src.CL___CIRCUIT_MISMATCH__CL,
src.NAME,
src.COUNTRY,
src.STATE,
src.CITY,
src.ROOM,
src.SHELF,
src.NOTES,
src.STATION,
src.HW_VERSION,
src.MANAGEABLE,
src.LAST_FAIL,
j27.ID AS RESOURCE_ID,
src.LAST_FAIL_CAUSE,
src.PROJECT_ID,
src.ADDRESS,
src.MODEL_NAME,
src.NOVACOLUNA,
src.CL___MUX_LOCAL_ID__CL AS ERP_CODE
FROM CLARO.TB___MUXS__TB src
LEFT JOIN TB___PROXIES__TB j1 ON j1.ERP_CODE = src.CL___PROXY_CODE__CL
LEFT JOIN TB___MODELS__TB j5 ON j5.ID = src.CL___MODEL_CODE__CL
LEFT JOIN VENDORS j14 ON j14.ID = src.CL___VENDOR_CODE__CL
LEFT JOIN PROVISIONING_RESOURCE j27 ON j27.ERP_CODE = src.RESOURCE_ID
WHERE NOT EXISTS (
    SELECT 1 FROM TB___MUXS__TB dest WHERE dest.ERP_CODE = src.CL___MUX_LOCAL_ID__CL
);
COMMIT;