-- Ordem: 042 | Tabela: DEVICE_DATA_FILE | Depth: 3
INSERT INTO CLARO.DEVICE_DATA_FILE (
ID,
DEVICE_RESOURCE_ID,
DEVICE_RESOURCE_ID,
DEVICE_RESOURCE_ID,
DATA_TYPE,
DATA_TYPE,
DATA_TYPE,
BLOB_DATA,
ERP_CODE
)
SELECT 
src.ID,
j104.RESOURCE_ID AS DEVICE_RESOURCE_ID,
j104.RESOURCE_ID AS DEVICE_RESOURCE_ID,
j104.RESOURCE_ID AS DEVICE_RESOURCE_ID,
j105.DATA_NAME AS DATA_TYPE,
j105.DATA_NAME AS DATA_TYPE,
j105.DATA_NAME AS DATA_TYPE,
src.BLOB_DATA,
TRIM(CAST(src.ID AS VARCHAR2(64))) AS ERP_CODE
FROM OI.DEVICE_DATA_FILE src
LEFT JOIN CLARO.TB___MUXS__TB j104 ON j104.ERP_CODE = TRIM(CAST(src.DEVICE_RESOURCE_ID AS VARCHAR2(64)))
LEFT JOIN CLARO.DEVICE_DATA_FILE_TYPE j105 ON j105.DATA_NAME = src.DATA_TYPE
WHERE NOT EXISTS (SELECT 1 FROM CLARO.DEVICE_DATA_FILE dest WHERE dest.ERP_CODE = TRIM(CAST(src.ID AS VARCHAR2(64))));
