-- Ordem: 042 | Tabela: VCG_MAPPING_PATH_SECTION | Depth: 2
INSERT INTO VCG_MAPPING_PATH_SECTION
(
PROXY_CODE,
DEV_NO,
DEV_LOCAL_ID,
SLOT_NO,
PORT_NO,
TX_PORT_NO,
TX_SQN,
RX_PORT_NO,
RX_SQN,
SQM_ALARM,
NOVACOLUNA,
ERP_CODE
)
SELECT
src.PROXY_CODE,
src.DEV_NO,
src.DEV_LOCAL_ID,
src.SLOT_NO,
src.PORT_NO,
src.TX_PORT_NO,
src.TX_SQN,
src.RX_PORT_NO,
src.RX_SQN,
src.SQM_ALARM,
src.NOVACOLUNA,
src.ID_PATH_SECTION AS ERP_CODE
FROM CLARO.VCG_MAPPING_PATH_SECTION src
LEFT JOIN PATH_SECTION j1 ON j1.ERP_CODE = src.ID_PATH_SECTION
WHERE NOT EXISTS (
    SELECT 1 FROM VCG_MAPPING_PATH_SECTION dest WHERE dest.ERP_CODE = src.ID_PATH_SECTION
);
COMMIT;