-- Ordem: 043 | Tabela: DEVICE_NODE | Depth: 3
INSERT INTO CLARO.DEVICE_NODE (
GRAPHIC_ID,
DEVICE_NODE_PROXY_CODE,
DEVICE_NODE_DEV_NO,
DEVICE_NODE_DEV_LOCAL_ID
)
SELECT 
j108.GRAPHIC_ID AS GRAPHIC_ID,
src.DEVICE_NODE_PROXY_CODE,
src.DEVICE_NODE_DEV_NO,
src.DEVICE_NODE_DEV_LOCAL_ID
FROM OI.DEVICE_NODE src
LEFT JOIN CLARO.NODE j108 ON j108.ERP_CODE = TRIM(CAST(src.GRAPHIC_ID AS VARCHAR2(64)))
WHERE NOT EXISTS (SELECT 1 FROM CLARO.DEVICE_NODE dest WHERE dest.ERP_CODE = TRIM(CAST(src.GRAPHIC_ID AS VARCHAR2(64))));
COMMIT;