-- Ordem: 043 | Tabela: CIRCUIT_COMMENT | Depth: 3
INSERT INTO CIRCUIT_COMMENT
(
ID_COMMENT,
COMMENT_VALUE,
NOVACOLUNA,
ERP_CODE
)
SELECT
j2.ID AS ID_COMMENT,
src.COMMENT_VALUE,
src.NOVACOLUNA,
src.ID_CIRCUIT AS ERP_CODE
FROM CLARO.CIRCUIT_COMMENT src
LEFT JOIN CIRCUIT j1 ON j1.ERP_CODE = src.ID_CIRCUIT
LEFT JOIN COMMENT_LABEL j2 ON j2.ID = src.ID_COMMENT
WHERE NOT EXISTS (
    SELECT 1 FROM CIRCUIT_COMMENT dest WHERE dest.ERP_CODE = src.ID_CIRCUIT
);
COMMIT;