-- Ordem: 044 | Tabela: CIRCUIT_OBJECT | Depth: 3
INSERT INTO CIRCUIT_OBJECT
(
ID_CIRCUIT,
OBJECT,
OBJ_INSTANCE,
OBJ_VALUE,
NOVACOLUNA,
ERP_CODE
)
SELECT
j1.ID AS ID_CIRCUIT,
src.OBJECT,
src.OBJ_INSTANCE,
src.OBJ_VALUE,
src.NOVACOLUNA,
src.ID_CIRCUIT AS ERP_CODE
FROM CLARO.CIRCUIT_OBJECT src
LEFT JOIN CIRCUIT j1 ON j1.ERP_CODE = src.ID_CIRCUIT
WHERE NOT EXISTS (
    SELECT 1 FROM CIRCUIT_OBJECT dest WHERE dest.ERP_CODE = src.ID_CIRCUIT
);
COMMIT;