-- Ordem: 044 | Tabela: GROUP_NODE | Depth: 3
INSERT INTO CLARO.GROUP_NODE (
GRAPHIC_ID,
GROUP_NODE_NAME,
GROUP_NODE_STATUS,
GROUP_NODE_IMAGE,
CIRCUIT_MISMATCH,
ZOOM_FACTOR,
OFFLINE_CODE
)
SELECT 
j143.GRAPHIC_ID AS GRAPHIC_ID,
src.GROUP_NODE_NAME,
src.GROUP_NODE_STATUS,
src.GROUP_NODE_IMAGE,
src.CIRCUIT_MISMATCH,
src.ZOOM_FACTOR,
src.OFFLINE_CODE
FROM OI.GROUP_NODE src
LEFT JOIN CLARO.NODE j143 ON j143.ERP_CODE = TRIM(CAST(src.GRAPHIC_ID AS VARCHAR2(64)))
WHERE NOT EXISTS (SELECT 1 FROM CLARO.GROUP_NODE dest WHERE dest.ERP_CODE = TRIM(CAST(src.GRAPHIC_ID AS VARCHAR2(64))));
COMMIT;