-- Ordem: 045 | Tabela: CIRCUIT_SITUATION_BY_DEVICE | Depth: 3
INSERT INTO CIRCUIT_SITUATION_BY_DEVICE
(
ID_CIRCUIT,
PROXY_CODE,
DEV_NO,
SITUATION,
NOVACOLUNA,
ERP_CODE
)
SELECT
j1.ID AS ID_CIRCUIT,
src.PROXY_CODE,
src.DEV_NO,
src.SITUATION,
src.NOVACOLUNA,
src.DEV_LOCAL_ID AS ERP_CODE
FROM CLARO.CIRCUIT_SITUATION_BY_DEVICE src
LEFT JOIN CIRCUIT j1 ON j1.ERP_CODE = src.ID_CIRCUIT
WHERE NOT EXISTS (
    SELECT 1 FROM CIRCUIT_SITUATION_BY_DEVICE dest WHERE dest.ERP_CODE = src.DEV_LOCAL_ID
);
COMMIT;