-- Ordem: 046 | Tabela: METRO_PORT_VLANS | Depth: 3
INSERT INTO CLARO.METRO_PORT_VLANS (
PROXY_CODE,
DEV_NO,
DEV_LOCAL_ID,
SLOT,
PORT,
VLAN_RANGE_START,
VLAN_RANGE_END,
MEMBERSHIP_TYPE,
CONTROL
)
SELECT 
j175.CL___PROXY_CODE__CL AS PROXY_CODE,
j175.CL___MUX_NO__CL AS DEV_NO,
j175.CL___MUX_LOCAL_ID__CL AS DEV_LOCAL_ID,
src.SLOT,
src.PORT,
src.VLAN_RANGE_START,
src.VLAN_RANGE_END,
src.MEMBERSHIP_TYPE,
src.CONTROL
FROM OI.METRO_PORT_VLANS src
LEFT JOIN CLARO.TB___MUXS__TB j175 ON j175.ERP_CODE = LOWER(RAWTOHEX(STANDARD_HASH(TRIM(CAST(src.PROXY_CODE AS VARCHAR2(100))) || '|' || TRIM(CAST(src.DEV_NO AS VARCHAR2(100))) || '|' || TRIM(CAST(src.DEV_LOCAL_ID AS VARCHAR2(100))), 'MD5')))
WHERE NOT EXISTS (SELECT 1 FROM CLARO.METRO_PORT_VLANS dest WHERE dest.ERP_CODE = LOWER(RAWTOHEX(STANDARD_HASH(TRIM(CAST(src.PROXY_CODE AS VARCHAR2(100))) || '|' || TRIM(CAST(src.DEV_NO AS VARCHAR2(100))) || '|' || TRIM(CAST(src.DEV_LOCAL_ID AS VARCHAR2(100))) || '|' || TRIM(CAST(src.SLOT AS VARCHAR2(100))) || '|' || TRIM(CAST(src.PORT AS VARCHAR2(100))) || '|' || TRIM(CAST(src.VLAN_RANGE_START AS VARCHAR2(100))), 'MD5'))));
COMMIT;