-- Ordem: 046 | Tabela: CONNECTION | Depth: 3
INSERT INTO CONNECTION
(
CONNECTION_A_END_NODE,
CONNECTION_Z_END_NODE,
CONNECTION_STATUS,
NOVACOLUNA,
ERP_CODE
)
SELECT
j2.ID AS CONNECTION_A_END_NODE,
j3.ID AS CONNECTION_Z_END_NODE,
src.CONNECTION_STATUS,
src.NOVACOLUNA,
src.GRAPHIC_ID AS ERP_CODE
FROM CLARO.CONNECTION src
LEFT JOIN GRAPHIC j1 ON j1.ERP_CODE = src.GRAPHIC_ID
LEFT JOIN NODE j2 ON j2.ERP_CODE = src.CONNECTION_A_END_NODE
LEFT JOIN NODE j3 ON j3.ERP_CODE = src.CONNECTION_Z_END_NODE
WHERE NOT EXISTS (
    SELECT 1 FROM CONNECTION dest WHERE dest.ERP_CODE = src.GRAPHIC_ID
);
COMMIT;