-- Ordem: 047 | Tabela: METRO_VLAN_GROUP | Depth: 3
INSERT INTO CLARO.METRO_VLAN_GROUP (
VLAN_GROUP_ID,
PROXY_CODE,
DEV_NO,
DEV_LOCAL_ID,
VLAN_GROUP_NUMBER,
ENABLED,
CONTROL,
ERP_CODE
)
SELECT 
src.VLAN_GROUP_ID,
j176.CL___PROXY_CODE__CL AS PROXY_CODE,
j176.CL___MUX_NO__CL AS DEV_NO,
j176.CL___MUX_LOCAL_ID__CL AS DEV_LOCAL_ID,
src.VLAN_GROUP_NUMBER,
src.ENABLED,
src.CONTROL,
TRIM(CAST(src.VLAN_GROUP_ID AS VARCHAR2(64))) AS ERP_CODE
FROM OI.METRO_VLAN_GROUP src
LEFT JOIN CLARO.TB___MUXS__TB j176 ON j176.ERP_CODE = LOWER(RAWTOHEX(STANDARD_HASH(TRIM(CAST(src.PROXY_CODE AS VARCHAR2(100))) || '|' || TRIM(CAST(src.DEV_NO AS VARCHAR2(100))) || '|' || TRIM(CAST(src.DEV_LOCAL_ID AS VARCHAR2(100))), 'MD5')))
WHERE NOT EXISTS (SELECT 1 FROM CLARO.METRO_VLAN_GROUP dest WHERE dest.ERP_CODE = TRIM(CAST(src.VLAN_GROUP_ID AS VARCHAR2(64))));
