-- Ordem: 047 | Tabela: CROSS_PATH_SECTION_TS | Depth: 3
INSERT INTO CROSS_PATH_SECTION_TS
(
ID_PATH_SECTION,
TS_SRC,
TS_DST,
NOVACOLUNA,
ERP_CODE
)
SELECT
j1.ID AS ID_PATH_SECTION,
src.TS_SRC,
src.TS_DST,
src.NOVACOLUNA,
src.ID_PATH_SECTION AS ERP_CODE
FROM CLARO.CROSS_PATH_SECTION_TS src
LEFT JOIN CROSS_PATH_SECTION j1 ON j1.ERP_CODE = src.ID_PATH_SECTION
WHERE NOT EXISTS (
    SELECT 1 FROM CROSS_PATH_SECTION_TS dest WHERE dest.ERP_CODE = src.ID_PATH_SECTION
);
COMMIT;