-- Ordem: 048 | Tabela: SDH_MAPPING | Depth: 3
INSERT INTO CLARO.SDH_MAPPING (
SDH_MAPPING_ID,
PROXY_CODE,
MUX_NO,
MUX_LOCAL_ID,
SLOT_SRC,
PORT_SRC,
SLOT_DST,
PORT_DST,
PROT_TYPE,
CONTROL,
ERP_CODE
)
SELECT 
src.SDH_MAPPING_ID,
j321.CL___PROXY_CODE__CL AS PROXY_CODE,
j321.CL___MUX_NO__CL AS MUX_NO,
j321.CL___MUX_LOCAL_ID__CL AS MUX_LOCAL_ID,
src.SLOT_SRC,
src.PORT_SRC,
src.SLOT_DST,
src.PORT_DST,
src.PROT_TYPE,
src.CONTROL,
TRIM(CAST(src.SDH_MAPPING_ID AS VARCHAR2(64))) AS ERP_CODE
FROM OI.SDH_MAPPING src
LEFT JOIN CLARO.TB___MUXS__TB j321 ON j321.ERP_CODE = LOWER(RAWTOHEX(STANDARD_HASH(TRIM(CAST(src.PROXY_CODE AS VARCHAR2(100))) || '|' || TRIM(CAST(src.MUX_NO AS VARCHAR2(100))) || '|' || TRIM(CAST(src.MUX_LOCAL_ID AS VARCHAR2(100))), 'MD5')))
WHERE NOT EXISTS (SELECT 1 FROM CLARO.SDH_MAPPING dest WHERE dest.ERP_CODE = TRIM(CAST(src.SDH_MAPPING_ID AS VARCHAR2(64))));
