-- Ordem: 048 | Tabela: DEVICE_DATA_FILE | Depth: 3
INSERT INTO DEVICE_DATA_FILE
(
DEVICE_RESOURCE_ID,
DATA_TYPE,
BLOB_DATA,
NOVACOLUNA,
ERP_CODE
)
SELECT
j2.ID AS DEVICE_RESOURCE_ID,
j3.ID AS DATA_TYPE,
src.BLOB_DATA,
src.NOVACOLUNA,
src.ID AS ERP_CODE
FROM CLARO.DEVICE_DATA_FILE src
LEFT JOIN TB___MUXS__TB j2 ON j2.ERP_CODE = src.DEVICE_RESOURCE_ID
LEFT JOIN DEVICE_DATA_FILE_TYPE j3 ON j3.ID = src.DATA_TYPE
WHERE NOT EXISTS (
    SELECT 1 FROM DEVICE_DATA_FILE dest WHERE dest.ERP_CODE = src.ID
);
COMMIT;