-- Ordem: 049 | Tabela: DEVICE_NODE | Depth: 3
INSERT INTO DEVICE_NODE
(
GRAPHIC_ID,
DEVICE_NODE_PROXY_CODE,
DEVICE_NODE_DEV_NO,
DEVICE_NODE_DEV_LOCAL_ID,
NOVACOLUNA,
ERP_CODE
)
SELECT
j1.ID AS GRAPHIC_ID,
src.DEVICE_NODE_PROXY_CODE,
src.DEVICE_NODE_DEV_NO,
src.DEVICE_NODE_DEV_LOCAL_ID,
src.NOVACOLUNA,
src.GRAPHIC_ID AS ERP_CODE
FROM CLARO.DEVICE_NODE src
LEFT JOIN NODE j1 ON j1.ERP_CODE = src.GRAPHIC_ID
WHERE NOT EXISTS (
    SELECT 1 FROM DEVICE_NODE dest WHERE dest.ERP_CODE = src.GRAPHIC_ID
);
COMMIT;