-- Ordem: 049 | Tabela: SDH_MAPPING_DM800 | Depth: 3
INSERT INTO CLARO.SDH_MAPPING_DM800 (
SDH_MAPPING_ID,
PROXY_CODE,
MUX_NO,
MUX_LOCAL_ID,
MAPPING_TYPE,
SLOT_SRC,
PORT_SRC,
SLOT_DST,
PORT_DST,
CONTROL
)
SELECT 
src.SDH_MAPPING_ID,
j323.CL___PROXY_CODE__CL AS PROXY_CODE,
j323.CL___MUX_NO__CL AS MUX_NO,
j323.CL___MUX_LOCAL_ID__CL AS MUX_LOCAL_ID,
src.MAPPING_TYPE,
src.SLOT_SRC,
src.PORT_SRC,
src.SLOT_DST,
src.PORT_DST,
src.CONTROL
FROM OI.SDH_MAPPING_DM800 src
LEFT JOIN CLARO.TB___MUXS__TB j323 ON j323.ERP_CODE = LOWER(RAWTOHEX(STANDARD_HASH(TRIM(CAST(src.PROXY_CODE AS VARCHAR2(100))) || '|' || TRIM(CAST(src.MUX_NO AS VARCHAR2(100))) || '|' || TRIM(CAST(src.MUX_LOCAL_ID AS VARCHAR2(100))), 'MD5')))
WHERE NOT EXISTS (SELECT 1 FROM CLARO.SDH_MAPPING_DM800 dest WHERE dest.ERP_CODE = TRIM(CAST(src.SDH_MAPPING_ID AS VARCHAR2(64))));
COMMIT;