-- Ordem: 050 | Tabela: GROUP_NODE | Depth: 3
INSERT INTO GROUP_NODE
(
GROUP_NODE_NAME,
GROUP_NODE_STATUS,
GROUP_NODE_IMAGE,
CIRCUIT_MISMATCH,
ZOOM_FACTOR,
OFFLINE_CODE,
NOVACOLUNA,
ERP_CODE
)
SELECT
src.GROUP_NODE_NAME,
src.GROUP_NODE_STATUS,
src.GROUP_NODE_IMAGE,
src.CIRCUIT_MISMATCH,
src.ZOOM_FACTOR,
src.OFFLINE_CODE,
src.NOVACOLUNA,
src.GRAPHIC_ID AS ERP_CODE
FROM CLARO.GROUP_NODE src
LEFT JOIN NODE j1 ON j1.ERP_CODE = src.GRAPHIC_ID
WHERE NOT EXISTS (
    SELECT 1 FROM GROUP_NODE dest WHERE dest.ERP_CODE = src.GRAPHIC_ID
);
COMMIT;