-- Ordem: 050 | Tabela: SLOT | Depth: 3
INSERT INTO CLARO.SLOT (
PROXY_CODE,
DEV_NO,
DEV_LOCAL_ID,
SLOT_NO,
SLOT_MODEL,
SLOT_STATUS,
SLOT_FW_VERSION,
SLOT_ID,
ERP_CODE
)
SELECT 
j336.CL___PROXY_CODE__CL AS PROXY_CODE,
j336.CL___MUX_NO__CL AS DEV_NO,
j336.CL___MUX_LOCAL_ID__CL AS DEV_LOCAL_ID,
src.SLOT_NO,
j337.CL___MODEL_CODE__CL AS SLOT_MODEL,
src.SLOT_STATUS,
src.SLOT_FW_VERSION,
src.SLOT_ID,
LOWER(RAWTOHEX(STANDARD_HASH(TRIM(CAST(src.PROXY_CODE AS VARCHAR2(100))) || '|' || TRIM(CAST(src.DEV_NO AS VARCHAR2(100))) || '|' || TRIM(CAST(src.DEV_LOCAL_ID AS VARCHAR2(100))) || '|' || TRIM(CAST(src.SLOT_NO AS VARCHAR2(100))), 'MD5'))) AS ERP_CODE
FROM OI.SLOT src
LEFT JOIN CLARO.TB___MUXS__TB j336 ON j336.ERP_CODE = LOWER(RAWTOHEX(STANDARD_HASH(TRIM(CAST(src.PROXY_CODE AS VARCHAR2(100))) || '|' || TRIM(CAST(src.DEV_NO AS VARCHAR2(100))) || '|' || TRIM(CAST(src.DEV_LOCAL_ID AS VARCHAR2(100))), 'MD5')))
LEFT JOIN CLARO.TB___MODELS__TB j337 ON j337.CL___MODEL_CODE__CL = src.SLOT_MODEL
WHERE NOT EXISTS (SELECT 1 FROM CLARO.SLOT dest WHERE dest.ERP_CODE = LOWER(RAWTOHEX(STANDARD_HASH(TRIM(CAST(src.PROXY_CODE AS VARCHAR2(100))) || '|' || TRIM(CAST(src.DEV_NO AS VARCHAR2(100))) || '|' || TRIM(CAST(src.DEV_LOCAL_ID AS VARCHAR2(100))) || '|' || TRIM(CAST(src.SLOT_NO AS VARCHAR2(100))), 'MD5'))));
