-- Ordem: 051 | Tabela: STP_CFG | Depth: 3
INSERT INTO CLARO.STP_CFG (
STP_CFG_ID,
PROXY_CODE,
DEV_NO,
DEV_LOCAL_ID,
DOMAIN_ID,
FORWARD_DELAY,
PRIORITY,
MAXAGE,
ENABLED,
HELLO_TIME,
MAX_HOPS,
CONTROL,
ERP_CODE
)
SELECT 
src.STP_CFG_ID,
j349.CL___PROXY_CODE__CL AS PROXY_CODE,
j349.CL___MUX_NO__CL AS DEV_NO,
j349.CL___MUX_LOCAL_ID__CL AS DEV_LOCAL_ID,
src.DOMAIN_ID,
src.FORWARD_DELAY,
src.PRIORITY,
src.MAXAGE,
src.ENABLED,
src.HELLO_TIME,
src.MAX_HOPS,
src.CONTROL,
TRIM(CAST(src.STP_CFG_ID AS VARCHAR2(64))) AS ERP_CODE
FROM OI.STP_CFG src
LEFT JOIN CLARO.TB___MUXS__TB j349 ON j349.ERP_CODE = LOWER(RAWTOHEX(STANDARD_HASH(TRIM(CAST(src.PROXY_CODE AS VARCHAR2(100))) || '|' || TRIM(CAST(src.DEV_NO AS VARCHAR2(100))) || '|' || TRIM(CAST(src.DEV_LOCAL_ID AS VARCHAR2(100))), 'MD5')))
WHERE NOT EXISTS (SELECT 1 FROM CLARO.STP_CFG dest WHERE dest.ERP_CODE = TRIM(CAST(src.STP_CFG_ID AS VARCHAR2(64))));
