-- Ordem: 052 | Tabela: METRO_PORT_VLANS | Depth: 3
INSERT INTO METRO_PORT_VLANS
(
PROXY_CODE,
DEV_NO,
SLOT,
PORT,
VLAN_RANGE_START,
VLAN_RANGE_END,
MEMBERSHIP_TYPE,
CONTROL,
NOVACOLUNA,
ERP_CODE
)
SELECT
j1.ID AS PROXY_CODE,
j2.ID AS DEV_NO,
src.SLOT,
src.PORT,
src.VLAN_RANGE_START,
src.VLAN_RANGE_END,
src.MEMBERSHIP_TYPE,
src.CONTROL,
src.NOVACOLUNA,
src.DEV_LOCAL_ID AS ERP_CODE
FROM CLARO.METRO_PORT_VLANS src
LEFT JOIN TB___MUXS__TB j1 ON j1.ERP_CODE = src.PROXY_CODE
LEFT JOIN TB___MUXS__TB j2 ON j2.ERP_CODE = src.DEV_NO
LEFT JOIN TB___MUXS__TB j3 ON j3.ERP_CODE = src.DEV_LOCAL_ID
WHERE NOT EXISTS (
    SELECT 1 FROM METRO_PORT_VLANS dest WHERE dest.ERP_CODE = src.DEV_LOCAL_ID
);
COMMIT;