-- Ordem: 053 | Tabela: METRO_VLAN_GROUP | Depth: 3
INSERT INTO METRO_VLAN_GROUP
(
PROXY_CODE,
DEV_NO,
DEV_LOCAL_ID,
VLAN_GROUP_NUMBER,
ENABLED,
CONTROL,
NOVACOLUNA,
ERP_CODE
)
SELECT
j2.ID AS PROXY_CODE,
j3.ID AS DEV_NO,
j4.ID AS DEV_LOCAL_ID,
src.VLAN_GROUP_NUMBER,
src.ENABLED,
src.CONTROL,
src.NOVACOLUNA,
src.VLAN_GROUP_ID AS ERP_CODE
FROM CLARO.METRO_VLAN_GROUP src
LEFT JOIN TB___MUXS__TB j2 ON j2.ERP_CODE = src.PROXY_CODE
LEFT JOIN TB___MUXS__TB j3 ON j3.ERP_CODE = src.DEV_NO
LEFT JOIN TB___MUXS__TB j4 ON j4.ERP_CODE = src.DEV_LOCAL_ID
WHERE NOT EXISTS (
    SELECT 1 FROM METRO_VLAN_GROUP dest WHERE dest.ERP_CODE = src.VLAN_GROUP_ID
);
COMMIT;