-- Ordem: 053 | Tabela: TB___MUXS_ALARMS__TB | Depth: 3
INSERT INTO CLARO.TB___MUXS_ALARMS__TB (
CL___PROXY_CODE__CL,
CL___MUX_NO__CL,
CL___MUX_LOCAL_ID__CL,
CL___ALARM_ID__CL,
UPTIME,
ERP_CODE
)
SELECT 
j368.CL___PROXY_CODE__CL AS CL___PROXY_CODE__CL,
j368.CL___MUX_NO__CL AS CL___MUX_NO__CL,
j368.CL___MUX_LOCAL_ID__CL AS CL___MUX_LOCAL_ID__CL,
j369.CL___ALARM_ID__CL AS CL___ALARM_ID__CL,
src.UPTIME,
LOWER(RAWTOHEX(STANDARD_HASH(TRIM(CAST(src.CL___PROXY_CODE__CL AS VARCHAR2(100))) || '|' || TRIM(CAST(src.CL___MUX_NO__CL AS VARCHAR2(100))) || '|' || TRIM(CAST(src.CL___MUX_LOCAL_ID__CL AS VARCHAR2(100))) || '|' || TRIM(CAST(src.CL___ALARM_ID__CL AS VARCHAR2(100))), 'MD5'))) AS ERP_CODE
FROM OI.TB___MUXS_ALARMS__TB src
LEFT JOIN CLARO.TB___MUXS__TB j368 ON j368.ERP_CODE = LOWER(RAWTOHEX(STANDARD_HASH(TRIM(CAST(src.CL___PROXY_CODE__CL AS VARCHAR2(100))) || '|' || TRIM(CAST(src.CL___MUX_NO__CL AS VARCHAR2(100))) || '|' || TRIM(CAST(src.CL___MUX_LOCAL_ID__CL AS VARCHAR2(100))), 'MD5')))
LEFT JOIN CLARO.TB___ALARMS__TB j369 ON j369.CL___ALARM_ID__CL = src.CL___ALARM_ID__CL
WHERE NOT EXISTS (SELECT 1 FROM CLARO.TB___MUXS_ALARMS__TB dest WHERE dest.ERP_CODE = LOWER(RAWTOHEX(STANDARD_HASH(TRIM(CAST(src.CL___PROXY_CODE__CL AS VARCHAR2(100))) || '|' || TRIM(CAST(src.CL___MUX_NO__CL AS VARCHAR2(100))) || '|' || TRIM(CAST(src.CL___MUX_LOCAL_ID__CL AS VARCHAR2(100))) || '|' || TRIM(CAST(src.CL___ALARM_ID__CL AS VARCHAR2(100))), 'MD5'))));
