-- Ordem: 054 | Tabela: TB___PORTS__TB | Depth: 3
INSERT INTO CLARO.TB___PORTS__TB (
CL___PROXY_CODE__CL,
CL___MUX_NO__CL,
CL___MUX_LOCAL_ID__CL,
CL___CARD_NO__CL,
CL___PORT_NO__CL,
CL___MODEL_CODE__CL,
CL___PORT_FIRM_VER__CL,
CL___PORT_STATUS__CL,
MASKED,
NAME,
NOTES,
LINK_NAME,
PORT_HW_VER,
RESOURCE_ID,
ERP_CODE
)
SELECT 
j380.CL___PROXY_CODE__CL AS CL___PROXY_CODE__CL,
j380.CL___MUX_NO__CL AS CL___MUX_NO__CL,
j380.CL___MUX_LOCAL_ID__CL AS CL___MUX_LOCAL_ID__CL,
src.CL___CARD_NO__CL,
src.CL___PORT_NO__CL,
src.CL___MODEL_CODE__CL,
src.CL___PORT_FIRM_VER__CL,
src.CL___PORT_STATUS__CL,
src.MASKED,
src.NAME,
src.NOTES,
src.LINK_NAME,
src.PORT_HW_VER,
src.RESOURCE_ID,
TRIM(CAST(src.RESOURCE_ID AS VARCHAR2(64))) AS ERP_CODE
FROM OI.TB___PORTS__TB src
LEFT JOIN CLARO.TB___MUXS__TB j380 ON j380.ERP_CODE = LOWER(RAWTOHEX(STANDARD_HASH(TRIM(CAST(src.CL___PROXY_CODE__CL AS VARCHAR2(100))) || '|' || TRIM(CAST(src.CL___MUX_NO__CL AS VARCHAR2(100))) || '|' || TRIM(CAST(src.CL___MUX_LOCAL_ID__CL AS VARCHAR2(100))), 'MD5')))
WHERE NOT EXISTS (SELECT 1 FROM CLARO.TB___PORTS__TB dest WHERE dest.ERP_CODE = TRIM(CAST(src.RESOURCE_ID AS VARCHAR2(64))));
