-- Ordem: 054 | Tabela: SDH_MAPPING | Depth: 3
INSERT INTO SDH_MAPPING
(
PROXY_CODE,
MUX_NO,
MUX_LOCAL_ID,
SLOT_SRC,
PORT_SRC,
SLOT_DST,
PORT_DST,
PROT_TYPE,
CONTROL,
NOVACOLUNA,
ERP_CODE
)
SELECT
j2.ID AS PROXY_CODE,
j3.ID AS MUX_NO,
j4.ID AS MUX_LOCAL_ID,
src.SLOT_SRC,
src.PORT_SRC,
src.SLOT_DST,
src.PORT_DST,
src.PROT_TYPE,
src.CONTROL,
src.NOVACOLUNA,
src.SDH_MAPPING_ID AS ERP_CODE
FROM CLARO.SDH_MAPPING src
LEFT JOIN TB___MUXS__TB j2 ON j2.ERP_CODE = src.PROXY_CODE
LEFT JOIN TB___MUXS__TB j3 ON j3.ERP_CODE = src.MUX_NO
LEFT JOIN TB___MUXS__TB j4 ON j4.ERP_CODE = src.MUX_LOCAL_ID
WHERE NOT EXISTS (
    SELECT 1 FROM SDH_MAPPING dest WHERE dest.ERP_CODE = src.SDH_MAPPING_ID
);
COMMIT;