-- Ordem: 055 | Tabela: TB___ST_MUXS__TB | Depth: 3
INSERT INTO CLARO.TB___ST_MUXS__TB (
CL___PROXY_CODE__CL,
CL___MUX_NO__CL,
CL___MUX_LOCAL_ID__CL,
CL___OBJECT__CL,
CL___OBJ_INSTANCE__CL,
CL___ST_MUX_VALUE__CL,
CL___VALID_OBJ__CL
)
SELECT 
j385.CL___PROXY_CODE__CL AS CL___PROXY_CODE__CL,
j385.CL___MUX_NO__CL AS CL___MUX_NO__CL,
j385.CL___MUX_LOCAL_ID__CL AS CL___MUX_LOCAL_ID__CL,
j386.CL___OBJECT__CL AS CL___OBJECT__CL,
src.CL___OBJ_INSTANCE__CL,
src.CL___ST_MUX_VALUE__CL,
src.CL___VALID_OBJ__CL
FROM OI.TB___ST_MUXS__TB src
LEFT JOIN CLARO.TB___MUXS__TB j385 ON j385.ERP_CODE = LOWER(RAWTOHEX(STANDARD_HASH(TRIM(CAST(src.CL___PROXY_CODE__CL AS VARCHAR2(100))) || '|' || TRIM(CAST(src.CL___MUX_NO__CL AS VARCHAR2(100))) || '|' || TRIM(CAST(src.CL___MUX_LOCAL_ID__CL AS VARCHAR2(100))), 'MD5')))
LEFT JOIN CLARO.TB___OBJECTS__TB j386 ON j386.CL___OBJECT__CL = src.CL___OBJECT__CL
WHERE NOT EXISTS (SELECT 1 FROM CLARO.TB___ST_MUXS__TB dest WHERE dest.ERP_CODE = LOWER(RAWTOHEX(STANDARD_HASH(TRIM(CAST(src.CL___PROXY_CODE__CL AS VARCHAR2(100))) || '|' || TRIM(CAST(src.CL___MUX_NO__CL AS VARCHAR2(100))) || '|' || TRIM(CAST(src.CL___MUX_LOCAL_ID__CL AS VARCHAR2(100))) || '|' || TRIM(CAST(src.CL___OBJECT__CL AS VARCHAR2(100))) || '|' || TRIM(CAST(src.CL___OBJ_INSTANCE__CL AS VARCHAR2(100))), 'MD5'))));
COMMIT;