-- Ordem: 056 | Tabela: VCG_MAPPING | Depth: 3
INSERT INTO CLARO.VCG_MAPPING (
PROXY_CODE,
DEVNO,
DEVLOCALID,
SLOTNO,
PORTNO,
TX_SQN,
RX_SQN,
CONTROL,
SQM_ALARM,
TX_PORTNO,
RX_PORTNO,
ERP_CODE
)
SELECT 
j411.CL___PROXY_CODE__CL AS PROXY_CODE,
j411.CL___MUX_NO__CL AS DEVNO,
j411.CL___MUX_LOCAL_ID__CL AS DEVLOCALID,
src.SLOTNO,
src.PORTNO,
src.TX_SQN,
src.RX_SQN,
src.CONTROL,
src.SQM_ALARM,
src.TX_PORTNO,
src.RX_PORTNO,
LOWER(RAWTOHEX(STANDARD_HASH(TRIM(CAST(src.PROXY_CODE AS VARCHAR2(100))) || '|' || TRIM(CAST(src.DEVNO AS VARCHAR2(100))) || '|' || TRIM(CAST(src.DEVLOCALID AS VARCHAR2(100))) || '|' || TRIM(CAST(src.SLOTNO AS VARCHAR2(100))) || '|' || TRIM(CAST(src.PORTNO AS VARCHAR2(100))), 'MD5'))) AS ERP_CODE
FROM OI.VCG_MAPPING src
LEFT JOIN CLARO.TB___MUXS__TB j411 ON j411.ERP_CODE = LOWER(RAWTOHEX(STANDARD_HASH(TRIM(CAST(src.PROXY_CODE AS VARCHAR2(100))) || '|' || TRIM(CAST(src.DEVNO AS VARCHAR2(100))) || '|' || TRIM(CAST(src.DEVLOCALID AS VARCHAR2(100))), 'MD5')))
WHERE NOT EXISTS (SELECT 1 FROM CLARO.VCG_MAPPING dest WHERE dest.ERP_CODE = LOWER(RAWTOHEX(STANDARD_HASH(TRIM(CAST(src.PROXY_CODE AS VARCHAR2(100))) || '|' || TRIM(CAST(src.DEVNO AS VARCHAR2(100))) || '|' || TRIM(CAST(src.DEVLOCALID AS VARCHAR2(100))) || '|' || TRIM(CAST(src.SLOTNO AS VARCHAR2(100))) || '|' || TRIM(CAST(src.PORTNO AS VARCHAR2(100))), 'MD5'))));
