-- Ordem: 056 | Tabela: SLOT | Depth: 3
INSERT INTO SLOT
(
PROXY_CODE,
DEV_NO,
SLOT_NO,
SLOT_MODEL,
SLOT_STATUS,
SLOT_FW_VERSION,
SLOT_ID,
NOVACOLUNA,
ERP_CODE
)
SELECT
j1.ID AS PROXY_CODE,
j2.ID AS DEV_NO,
src.SLOT_NO,
j5.ID AS SLOT_MODEL,
src.SLOT_STATUS,
src.SLOT_FW_VERSION,
src.SLOT_ID,
src.NOVACOLUNA,
src.DEV_LOCAL_ID AS ERP_CODE
FROM CLARO.SLOT src
LEFT JOIN TB___MUXS__TB j1 ON j1.ERP_CODE = src.PROXY_CODE
LEFT JOIN TB___MUXS__TB j2 ON j2.ERP_CODE = src.DEV_NO
LEFT JOIN TB___MUXS__TB j3 ON j3.ERP_CODE = src.DEV_LOCAL_ID
LEFT JOIN TB___MODELS__TB j5 ON j5.ID = src.SLOT_MODEL
WHERE NOT EXISTS (
    SELECT 1 FROM SLOT dest WHERE dest.ERP_CODE = src.DEV_LOCAL_ID
);
COMMIT;