-- Ordem: 057 | Tabela: VLAN_CFG | Depth: 3
INSERT INTO CLARO.VLAN_CFG (
VLAN_CFG_ID,
PROXY_CODE,
PROXY_CODE,
PROXY_CODE,
DEV_NO,
DEV_NO,
DEV_NO,
DEV_LOCAL_ID,
DEV_LOCAL_ID,
DEV_LOCAL_ID,
VLAN_NO,
OBJECT_NAME,
OBJECT_NAME,
OBJECT_NAME,
OBJECT_VALUE,
CONTROL,
INSTANCE
)
SELECT 
src.VLAN_CFG_ID,
j415.CL___PROXY_CODE__CL AS PROXY_CODE,
j415.CL___PROXY_CODE__CL AS PROXY_CODE,
j415.CL___PROXY_CODE__CL AS PROXY_CODE,
j415.CL___MUX_NO__CL AS DEV_NO,
j415.CL___MUX_NO__CL AS DEV_NO,
j415.CL___MUX_NO__CL AS DEV_NO,
j415.CL___MUX_LOCAL_ID__CL AS DEV_LOCAL_ID,
j415.CL___MUX_LOCAL_ID__CL AS DEV_LOCAL_ID,
j415.CL___MUX_LOCAL_ID__CL AS DEV_LOCAL_ID,
src.VLAN_NO,
j416.CL___OBJECT__CL AS OBJECT_NAME,
j416.CL___OBJECT__CL AS OBJECT_NAME,
j416.CL___OBJECT__CL AS OBJECT_NAME,
src.OBJECT_VALUE,
src.CONTROL,
src.INSTANCE
FROM OI.VLAN_CFG src
LEFT JOIN CLARO.TB___MUXS__TB j415 ON j415.ERP_CODE = LOWER(RAWTOHEX(STANDARD_HASH(TRIM(CAST(src.PROXY_CODE AS VARCHAR2(100))) || '|' || TRIM(CAST(src.DEV_NO AS VARCHAR2(100))) || '|' || TRIM(CAST(src.DEV_LOCAL_ID AS VARCHAR2(100))), 'MD5')))
LEFT JOIN CLARO.TB___OBJECTS__TB j416 ON j416.CL___OBJECT__CL = src.OBJECT_NAME
WHERE NOT EXISTS (SELECT 1 FROM CLARO.VLAN_CFG dest WHERE dest.ERP_CODE = TRIM(CAST(src.VLAN_CFG_ID AS VARCHAR2(64))));
COMMIT;