-- Ordem: 057 | Tabela: STP_CFG | Depth: 3
INSERT INTO STP_CFG
(
PROXY_CODE,
DEV_NO,
DEV_LOCAL_ID,
DOMAIN_ID,
FORWARD_DELAY,
PRIORITY,
MAXAGE,
ENABLED,
HELLO_TIME,
MAX_HOPS,
CONTROL,
NOVACOLUNA,
ERP_CODE
)
SELECT
j2.ID AS PROXY_CODE,
j3.ID AS DEV_NO,
j4.ID AS DEV_LOCAL_ID,
src.DOMAIN_ID,
src.FORWARD_DELAY,
src.PRIORITY,
src.MAXAGE,
src.ENABLED,
src.HELLO_TIME,
src.MAX_HOPS,
src.CONTROL,
src.NOVACOLUNA,
src.STP_CFG_ID AS ERP_CODE
FROM CLARO.STP_CFG src
LEFT JOIN TB___MUXS__TB j2 ON j2.ERP_CODE = src.PROXY_CODE
LEFT JOIN TB___MUXS__TB j3 ON j3.ERP_CODE = src.DEV_NO
LEFT JOIN TB___MUXS__TB j4 ON j4.ERP_CODE = src.DEV_LOCAL_ID
WHERE NOT EXISTS (
    SELECT 1 FROM STP_CFG dest WHERE dest.ERP_CODE = src.STP_CFG_ID
);
COMMIT;