-- Ordem: 058 | Tabela: LINK | Depth: 4
INSERT INTO CLARO.LINK (
LINK_ID,
LINK_NAME,
LINK_A_END_DEVICE,
LINK_Z_END_DEVICE,
LINK_STATUS,
SITUATION,
ERP_CODE
)
SELECT 
src.LINK_ID,
src.LINK_NAME,
j153.GRAPHIC_ID AS LINK_A_END_DEVICE,
j154.GRAPHIC_ID AS LINK_Z_END_DEVICE,
src.LINK_STATUS,
src.SITUATION,
TRIM(CAST(src.LINK_ID AS VARCHAR2(64))) AS ERP_CODE
FROM OI.LINK src
LEFT JOIN CLARO.DEVICE_NODE j153 ON j153.ERP_CODE = TRIM(CAST(src.LINK_A_END_DEVICE AS VARCHAR2(64)))
LEFT JOIN CLARO.DEVICE_NODE j154 ON j154.ERP_CODE = TRIM(CAST(src.LINK_Z_END_DEVICE AS VARCHAR2(64)))
WHERE NOT EXISTS (SELECT 1 FROM CLARO.LINK dest WHERE dest.ERP_CODE = TRIM(CAST(src.LINK_ID AS VARCHAR2(64))));
