-- Ordem: 059 | Tabela: TB___MUXS_ALARMS__TB | Depth: 3
INSERT INTO TB___MUXS_ALARMS__TB
(
CL___PROXY_CODE__CL,
CL___MUX_NO__CL,
CL___MUX_LOCAL_ID__CL,
UPTIME,
NOVACOLUNA,
ERP_CODE
)
SELECT
j1.ID AS CL___PROXY_CODE__CL,
j2.ID AS CL___MUX_NO__CL,
j3.ID AS CL___MUX_LOCAL_ID__CL,
src.UPTIME,
src.NOVACOLUNA,
src.CL___ALARM_ID__CL AS ERP_CODE
FROM CLARO.TB___MUXS_ALARMS__TB src
LEFT JOIN TB___MUXS__TB j1 ON j1.ERP_CODE = src.CL___PROXY_CODE__CL
LEFT JOIN TB___MUXS__TB j2 ON j2.ERP_CODE = src.CL___MUX_NO__CL
LEFT JOIN TB___MUXS__TB j3 ON j3.ERP_CODE = src.CL___MUX_LOCAL_ID__CL
LEFT JOIN TB___ALARMS__TB j4 ON j4.ID = src.CL___ALARM_ID__CL
WHERE NOT EXISTS (
    SELECT 1 FROM TB___MUXS_ALARMS__TB dest WHERE dest.ERP_CODE = src.CL___ALARM_ID__CL
);
COMMIT;