-- Ordem: 059 | Tabela: MATRIX_MAPPING | Depth: 4
INSERT INTO CLARO.MATRIX_MAPPING (
MATRIX_ID,
SLOT_NO,
PROTECTION_TYPE,
CONTROL,
PORT_NO,
PORT_NO_BACKUP
)
SELECT 
j166.MATRIX_ID AS MATRIX_ID,
src.SLOT_NO,
src.PROTECTION_TYPE,
src.CONTROL,
src.PORT_NO,
src.PORT_NO_BACKUP
FROM OI.MATRIX_MAPPING src
LEFT JOIN CLARO.MATRIX j166 ON j166.ERP_CODE = TRIM(CAST(src.MATRIX_ID AS VARCHAR2(64)))
WHERE NOT EXISTS (SELECT 1 FROM CLARO.MATRIX_MAPPING dest WHERE dest.ERP_CODE = TRIM(CAST(src.MATRIX_ID AS VARCHAR2(64))));
COMMIT;