-- Ordem: 060 | Tabela: METRO_VLAN_GROUP_VLANS | Depth: 4
INSERT INTO CLARO.METRO_VLAN_GROUP_VLANS (
VLAN_GROUP_ID,
BITMAP_INDEX,
VLANS_BITMAP
)
SELECT 
j178.VLAN_GROUP_ID AS VLAN_GROUP_ID,
src.BITMAP_INDEX,
src.VLANS_BITMAP
FROM OI.METRO_VLAN_GROUP_VLANS src
LEFT JOIN CLARO.METRO_VLAN_GROUP j178 ON j178.ERP_CODE = TRIM(CAST(src.VLAN_GROUP_ID AS VARCHAR2(64)))
WHERE NOT EXISTS (SELECT 1 FROM CLARO.METRO_VLAN_GROUP_VLANS dest WHERE dest.ERP_CODE = LOWER(RAWTOHEX(STANDARD_HASH(TRIM(CAST(src.VLAN_GROUP_ID AS VARCHAR2(100))) || '|' || TRIM(CAST(src.BITMAP_INDEX AS VARCHAR2(100))), 'MD5'))));
COMMIT;