-- Ordem: 060 | Tabela: TB___PORTS__TB | Depth: 3
INSERT INTO TB___PORTS__TB
(
CL___PROXY_CODE__CL,
CL___MUX_NO__CL,
CL___MUX_LOCAL_ID__CL,
CL___CARD_NO__CL,
CL___PORT_NO__CL,
CL___MODEL_CODE__CL,
CL___PORT_FIRM_VER__CL,
CL___PORT_STATUS__CL,
MASKED,
NAME,
NOTES,
LINK_NAME,
PORT_HW_VER,
NOVACOLUNA,
ERP_CODE
)
SELECT
j1.ID AS CL___PROXY_CODE__CL,
j2.ID AS CL___MUX_NO__CL,
j3.ID AS CL___MUX_LOCAL_ID__CL,
src.CL___CARD_NO__CL,
src.CL___PORT_NO__CL,
src.CL___MODEL_CODE__CL,
src.CL___PORT_FIRM_VER__CL,
src.CL___PORT_STATUS__CL,
src.MASKED,
src.NAME,
src.NOTES,
src.LINK_NAME,
src.PORT_HW_VER,
src.NOVACOLUNA,
src.RESOURCE_ID AS ERP_CODE
FROM CLARO.TB___PORTS__TB src
LEFT JOIN TB___MUXS__TB j1 ON j1.ERP_CODE = src.CL___PROXY_CODE__CL
LEFT JOIN TB___MUXS__TB j2 ON j2.ERP_CODE = src.CL___MUX_NO__CL
LEFT JOIN TB___MUXS__TB j3 ON j3.ERP_CODE = src.CL___MUX_LOCAL_ID__CL
WHERE NOT EXISTS (
    SELECT 1 FROM TB___PORTS__TB dest WHERE dest.ERP_CODE = src.RESOURCE_ID
);
COMMIT;