-- Ordem: 061 | Tabela: TB___ST_MUXS__TB | Depth: 3
INSERT INTO TB___ST_MUXS__TB
(
CL___PROXY_CODE__CL,
CL___MUX_NO__CL,
CL___OBJECT__CL,
CL___OBJ_INSTANCE__CL,
CL___ST_MUX_VALUE__CL,
CL___VALID_OBJ__CL,
NOVACOLUNA,
ERP_CODE
)
SELECT
j1.ID AS CL___PROXY_CODE__CL,
j2.ID AS CL___MUX_NO__CL,
j4.ID AS CL___OBJECT__CL,
src.CL___OBJ_INSTANCE__CL,
src.CL___ST_MUX_VALUE__CL,
src.CL___VALID_OBJ__CL,
src.NOVACOLUNA,
src.CL___MUX_LOCAL_ID__CL AS ERP_CODE
FROM CLARO.TB___ST_MUXS__TB src
LEFT JOIN TB___MUXS__TB j1 ON j1.ERP_CODE = src.CL___PROXY_CODE__CL
LEFT JOIN TB___MUXS__TB j2 ON j2.ERP_CODE = src.CL___MUX_NO__CL
LEFT JOIN TB___MUXS__TB j3 ON j3.ERP_CODE = src.CL___MUX_LOCAL_ID__CL
LEFT JOIN TB___OBJECTS__TB j4 ON j4.ID = src.CL___OBJECT__CL
WHERE NOT EXISTS (
    SELECT 1 FROM TB___ST_MUXS__TB dest WHERE dest.ERP_CODE = src.CL___MUX_LOCAL_ID__CL
);
COMMIT;