-- Ordem: 062 | Tabela: VCG_MAPPING | Depth: 3
INSERT INTO VCG_MAPPING
(
PROXY_CODE,
DEVNO,
DEVLOCALID,
SLOTNO,
PORTNO,
TX_SQN,
RX_SQN,
CONTROL,
SQM_ALARM,
TX_PORTNO,
RX_PORTNO,
NOVACOLUNA,
ERP_CODE
)
SELECT
j1.ID AS PROXY_CODE,
j2.ID AS DEVNO,
j3.ID AS DEVLOCALID,
src.SLOTNO,
src.PORTNO,
src.TX_SQN,
src.RX_SQN,
src.CONTROL,
src.SQM_ALARM,
src.TX_PORTNO,
src.RX_PORTNO,
src.NOVACOLUNA,
src.DEVLOCALID AS ERP_CODE
FROM CLARO.VCG_MAPPING src
LEFT JOIN TB___MUXS__TB j1 ON j1.ERP_CODE = src.PROXY_CODE
LEFT JOIN TB___MUXS__TB j2 ON j2.ERP_CODE = src.DEVNO
LEFT JOIN TB___MUXS__TB j3 ON j3.ERP_CODE = src.DEVLOCALID
WHERE NOT EXISTS (
    SELECT 1 FROM VCG_MAPPING dest WHERE dest.ERP_CODE = src.DEVLOCALID
);
COMMIT;