-- Ordem: 062 | Tabela: PORTS_TESTS | Depth: 4
INSERT INTO CLARO.PORTS_TESTS (
PROXY_CODE,
PROXY_CODE,
PROXY_CODE,
DEV_NO,
DEV_NO,
DEV_NO,
DEV_LOCAL_ID,
DEV_LOCAL_ID,
DEV_LOCAL_ID,
SLOT_NO,
SLOT_NO,
SLOT_NO,
PORT_NO,
PORT_NO,
PORT_NO,
TEST_ID,
TEST_SRC,
TEST_START_TIME
)
SELECT 
j230.CL___PROXY_CODE__CL AS PROXY_CODE,
j230.CL___PROXY_CODE__CL AS PROXY_CODE,
j230.CL___PROXY_CODE__CL AS PROXY_CODE,
j230.CL___MUX_NO__CL AS DEV_NO,
j230.CL___MUX_NO__CL AS DEV_NO,
j230.CL___MUX_NO__CL AS DEV_NO,
j230.CL___MUX_LOCAL_ID__CL AS DEV_LOCAL_ID,
j230.CL___MUX_LOCAL_ID__CL AS DEV_LOCAL_ID,
j230.CL___MUX_LOCAL_ID__CL AS DEV_LOCAL_ID,
j230.CL___CARD_NO__CL AS SLOT_NO,
j230.CL___CARD_NO__CL AS SLOT_NO,
j230.CL___CARD_NO__CL AS SLOT_NO,
j230.CL___PORT_NO__CL AS PORT_NO,
j230.CL___PORT_NO__CL AS PORT_NO,
j230.CL___PORT_NO__CL AS PORT_NO,
src.TEST_ID,
src.TEST_SRC,
src.TEST_START_TIME
FROM OI.PORTS_TESTS src
LEFT JOIN CLARO.TB___PORTS__TB j230 ON j230.ERP_CODE = LOWER(RAWTOHEX(STANDARD_HASH(TRIM(CAST(src.SLOT_NO AS VARCHAR2(100))) || '|' || TRIM(CAST(src.DEV_LOCAL_ID AS VARCHAR2(100))) || '|' || TRIM(CAST(src.DEV_NO AS VARCHAR2(100))) || '|' || TRIM(CAST(src.PORT_NO AS VARCHAR2(100))) || '|' || TRIM(CAST(src.PROXY_CODE AS VARCHAR2(100))), 'MD5')))
WHERE NOT EXISTS (SELECT 1 FROM CLARO.PORTS_TESTS dest WHERE dest.ERP_CODE = LOWER(RAWTOHEX(STANDARD_HASH(TRIM(CAST(src.PROXY_CODE AS VARCHAR2(100))) || '|' || TRIM(CAST(src.DEV_NO AS VARCHAR2(100))) || '|' || TRIM(CAST(src.DEV_LOCAL_ID AS VARCHAR2(100))) || '|' || TRIM(CAST(src.SLOT_NO AS VARCHAR2(100))) || '|' || TRIM(CAST(src.PORT_NO AS VARCHAR2(100))) || '|' || TRIM(CAST(src.TEST_ID AS VARCHAR2(100))), 'MD5'))));
COMMIT;