-- Ordem: 063 | Tabela: VLAN_CFG | Depth: 3
INSERT INTO VLAN_CFG
(
PROXY_CODE,
DEV_NO,
DEV_LOCAL_ID,
VLAN_NO,
OBJECT_NAME,
OBJECT_VALUE,
CONTROL,
INSTANCE,
NOVACOLUNA,
ERP_CODE
)
SELECT
j2.ID AS PROXY_CODE,
j3.ID AS DEV_NO,
j4.ID AS DEV_LOCAL_ID,
src.VLAN_NO,
j6.ID AS OBJECT_NAME,
src.OBJECT_VALUE,
src.CONTROL,
src.INSTANCE,
src.NOVACOLUNA,
src.VLAN_CFG_ID AS ERP_CODE
FROM CLARO.VLAN_CFG src
LEFT JOIN TB___MUXS__TB j2 ON j2.ERP_CODE = src.PROXY_CODE
LEFT JOIN TB___MUXS__TB j3 ON j3.ERP_CODE = src.DEV_NO
LEFT JOIN TB___MUXS__TB j4 ON j4.ERP_CODE = src.DEV_LOCAL_ID
LEFT JOIN TB___OBJECTS__TB j6 ON j6.ID = src.OBJECT_NAME
WHERE NOT EXISTS (
    SELECT 1 FROM VLAN_CFG dest WHERE dest.ERP_CODE = src.VLAN_CFG_ID
);
COMMIT;