-- Ordem: 063 | Tabela: SHORTCUT_NODE | Depth: 4
INSERT INTO CLARO.SHORTCUT_NODE (
GRAPHIC_ID,
SHORTCUT_NODE_TARGET,
ERP_CODE
)
SELECT 
j334.GRAPHIC_ID AS GRAPHIC_ID,
j333.GRAPHIC_ID AS SHORTCUT_NODE_TARGET,
TRIM(CAST(src.GRAPHIC_ID AS VARCHAR2(64))) AS ERP_CODE
FROM OI.SHORTCUT_NODE src
LEFT JOIN CLARO.GROUP_NODE j333 ON j333.ERP_CODE = TRIM(CAST(src.SHORTCUT_NODE_TARGET AS VARCHAR2(64)))
LEFT JOIN CLARO.NODE j334 ON j334.ERP_CODE = TRIM(CAST(src.GRAPHIC_ID AS VARCHAR2(64)))
WHERE NOT EXISTS (SELECT 1 FROM CLARO.SHORTCUT_NODE dest WHERE dest.ERP_CODE = TRIM(CAST(src.GRAPHIC_ID AS VARCHAR2(64))));
