-- Ordem: 064 | Tabela: STP_PROTECTED_VLAN_GROUPS | Depth: 4
INSERT INTO CLARO.STP_PROTECTED_VLAN_GROUPS (
STP_CFG_ID,
BITMAP_INDEX,
VLAN_GROUPS_BITMAP,
ERP_CODE
)
SELECT 
j357.STP_CFG_ID AS STP_CFG_ID,
src.BITMAP_INDEX,
src.VLAN_GROUPS_BITMAP,
LOWER(RAWTOHEX(STANDARD_HASH(TRIM(CAST(src.STP_CFG_ID AS VARCHAR2(100))) || '|' || TRIM(CAST(src.BITMAP_INDEX AS VARCHAR2(100))), 'MD5'))) AS ERP_CODE
FROM OI.STP_PROTECTED_VLAN_GROUPS src
LEFT JOIN CLARO.STP_CFG j357 ON j357.ERP_CODE = TRIM(CAST(src.STP_CFG_ID AS VARCHAR2(64)))
WHERE NOT EXISTS (SELECT 1 FROM CLARO.STP_PROTECTED_VLAN_GROUPS dest WHERE dest.ERP_CODE = LOWER(RAWTOHEX(STANDARD_HASH(TRIM(CAST(src.STP_CFG_ID AS VARCHAR2(100))) || '|' || TRIM(CAST(src.BITMAP_INDEX AS VARCHAR2(100))), 'MD5'))));
