-- Ordem: 064 | Tabela: LINK | Depth: 4
INSERT INTO LINK
(
LINK_NAME,
LINK_A_END_DEVICE,
LINK_Z_END_DEVICE,
LINK_STATUS,
SITUATION,
NOVACOLUNA,
ERP_CODE
)
SELECT
src.LINK_NAME,
j3.ID AS LINK_A_END_DEVICE,
j4.ID AS LINK_Z_END_DEVICE,
src.LINK_STATUS,
src.SITUATION,
src.NOVACOLUNA,
src.LINK_ID AS ERP_CODE
FROM CLARO.LINK src
LEFT JOIN DEVICE_NODE j3 ON j3.ERP_CODE = src.LINK_A_END_DEVICE
LEFT JOIN DEVICE_NODE j4 ON j4.ERP_CODE = src.LINK_Z_END_DEVICE
WHERE NOT EXISTS (
    SELECT 1 FROM LINK dest WHERE dest.ERP_CODE = src.LINK_ID
);
COMMIT;