-- Ordem: 065 | Tabela: MATRIX_MAPPING | Depth: 4
INSERT INTO MATRIX_MAPPING
(
MATRIX_ID,
SLOT_NO,
PROTECTION_TYPE,
CONTROL,
PORT_NO,
PORT_NO_BACKUP,
NOVACOLUNA,
ERP_CODE
)
SELECT
j1.ID AS MATRIX_ID,
src.SLOT_NO,
src.PROTECTION_TYPE,
src.CONTROL,
src.PORT_NO,
src.PORT_NO_BACKUP,
src.NOVACOLUNA,
src.MATRIX_ID AS ERP_CODE
FROM CLARO.MATRIX_MAPPING src
LEFT JOIN MATRIX j1 ON j1.ERP_CODE = src.MATRIX_ID
WHERE NOT EXISTS (
    SELECT 1 FROM MATRIX_MAPPING dest WHERE dest.ERP_CODE = src.MATRIX_ID
);
COMMIT;