-- Ordem: 066 | Tabela: METRO_VLAN_GROUP_VLANS | Depth: 4
INSERT INTO METRO_VLAN_GROUP_VLANS
(
VLAN_GROUP_ID,
VLANS_BITMAP,
NOVACOLUNA,
ERP_CODE
)
SELECT
j1.ID AS VLAN_GROUP_ID,
src.VLANS_BITMAP,
src.NOVACOLUNA,
src.BITMAP_INDEX AS ERP_CODE
FROM CLARO.METRO_VLAN_GROUP_VLANS src
LEFT JOIN METRO_VLAN_GROUP j1 ON j1.ERP_CODE = src.VLAN_GROUP_ID
WHERE NOT EXISTS (
    SELECT 1 FROM METRO_VLAN_GROUP_VLANS dest WHERE dest.ERP_CODE = src.BITMAP_INDEX
);
COMMIT;