-- Ordem: 066 | Tabela: TB___PORTS_ALARMS__TB | Depth: 4
INSERT INTO CLARO.TB___PORTS_ALARMS__TB (
CL___PROXY_CODE__CL,
CL___PROXY_CODE__CL,
CL___PROXY_CODE__CL,
CL___MUX_NO__CL,
CL___MUX_NO__CL,
CL___MUX_NO__CL,
CL___MUX_LOCAL_ID__CL,
CL___MUX_LOCAL_ID__CL,
CL___MUX_LOCAL_ID__CL,
CL___CARD_NO__CL,
CL___CARD_NO__CL,
CL___CARD_NO__CL,
CL___PORT_NO__CL,
CL___PORT_NO__CL,
CL___PORT_NO__CL,
CL___ALARM_ID__CL,
UPTIME,
ERP_CODE
)
SELECT 
j378.CL___PROXY_CODE__CL AS CL___PROXY_CODE__CL,
j378.CL___PROXY_CODE__CL AS CL___PROXY_CODE__CL,
j378.CL___PROXY_CODE__CL AS CL___PROXY_CODE__CL,
j378.CL___MUX_NO__CL AS CL___MUX_NO__CL,
j378.CL___MUX_NO__CL AS CL___MUX_NO__CL,
j378.CL___MUX_NO__CL AS CL___MUX_NO__CL,
j378.CL___MUX_LOCAL_ID__CL AS CL___MUX_LOCAL_ID__CL,
j378.CL___MUX_LOCAL_ID__CL AS CL___MUX_LOCAL_ID__CL,
j378.CL___MUX_LOCAL_ID__CL AS CL___MUX_LOCAL_ID__CL,
j378.CL___CARD_NO__CL AS CL___CARD_NO__CL,
j378.CL___CARD_NO__CL AS CL___CARD_NO__CL,
j378.CL___CARD_NO__CL AS CL___CARD_NO__CL,
j378.CL___PORT_NO__CL AS CL___PORT_NO__CL,
j378.CL___PORT_NO__CL AS CL___PORT_NO__CL,
j378.CL___PORT_NO__CL AS CL___PORT_NO__CL,
j379.CL___ALARM_ID__CL AS CL___ALARM_ID__CL,
src.UPTIME,
LOWER(RAWTOHEX(STANDARD_HASH(TRIM(CAST(src.CL___PROXY_CODE__CL AS VARCHAR2(100))) || '|' || TRIM(CAST(src.CL___MUX_NO__CL AS VARCHAR2(100))) || '|' || TRIM(CAST(src.CL___MUX_LOCAL_ID__CL AS VARCHAR2(100))) || '|' || TRIM(CAST(src.CL___CARD_NO__CL AS VARCHAR2(100))) || '|' || TRIM(CAST(src.CL___PORT_NO__CL AS VARCHAR2(100))) || '|' || TRIM(CAST(src.CL___ALARM_ID__CL AS VARCHAR2(100))), 'MD5'))) AS ERP_CODE
FROM OI.TB___PORTS_ALARMS__TB src
LEFT JOIN CLARO.TB___PORTS__TB j378 ON j378.ERP_CODE = LOWER(RAWTOHEX(STANDARD_HASH(TRIM(CAST(src.CL___CARD_NO__CL AS VARCHAR2(100))) || '|' || TRIM(CAST(src.CL___MUX_LOCAL_ID__CL AS VARCHAR2(100))) || '|' || TRIM(CAST(src.CL___MUX_NO__CL AS VARCHAR2(100))) || '|' || TRIM(CAST(src.CL___PORT_NO__CL AS VARCHAR2(100))) || '|' || TRIM(CAST(src.CL___PROXY_CODE__CL AS VARCHAR2(100))), 'MD5')))
LEFT JOIN CLARO.TB___ALARMS__TB j379 ON j379.CL___ALARM_ID__CL = src.CL___ALARM_ID__CL
WHERE NOT EXISTS (SELECT 1 FROM CLARO.TB___PORTS_ALARMS__TB dest WHERE dest.ERP_CODE = LOWER(RAWTOHEX(STANDARD_HASH(TRIM(CAST(src.CL___PROXY_CODE__CL AS VARCHAR2(100))) || '|' || TRIM(CAST(src.CL___MUX_NO__CL AS VARCHAR2(100))) || '|' || TRIM(CAST(src.CL___MUX_LOCAL_ID__CL AS VARCHAR2(100))) || '|' || TRIM(CAST(src.CL___CARD_NO__CL AS VARCHAR2(100))) || '|' || TRIM(CAST(src.CL___PORT_NO__CL AS VARCHAR2(100))) || '|' || TRIM(CAST(src.CL___ALARM_ID__CL AS VARCHAR2(100))), 'MD5'))));
