-- Ordem: 067 | Tabela: TB___ST_PORTS__TB | Depth: 4
INSERT INTO CLARO.TB___ST_PORTS__TB (
CL___PROXY_CODE__CL,
CL___PROXY_CODE__CL,
CL___PROXY_CODE__CL,
CL___MUX_NO__CL,
CL___MUX_NO__CL,
CL___MUX_NO__CL,
CL___MUX_LOCAL_ID__CL,
CL___MUX_LOCAL_ID__CL,
CL___MUX_LOCAL_ID__CL,
CL___CARD_NO__CL,
CL___CARD_NO__CL,
CL___CARD_NO__CL,
CL___PORT_NO__CL,
CL___PORT_NO__CL,
CL___PORT_NO__CL,
CL___OBJECT__CL,
CL___OBJ_INSTANCE__CL,
CL___ST_PORT_VALUE__CL,
CL___VALID_OBJ__CL,
ERP_CODE
)
SELECT 
j387.CL___PROXY_CODE__CL AS CL___PROXY_CODE__CL,
j387.CL___PROXY_CODE__CL AS CL___PROXY_CODE__CL,
j387.CL___PROXY_CODE__CL AS CL___PROXY_CODE__CL,
j387.CL___MUX_NO__CL AS CL___MUX_NO__CL,
j387.CL___MUX_NO__CL AS CL___MUX_NO__CL,
j387.CL___MUX_NO__CL AS CL___MUX_NO__CL,
j387.CL___MUX_LOCAL_ID__CL AS CL___MUX_LOCAL_ID__CL,
j387.CL___MUX_LOCAL_ID__CL AS CL___MUX_LOCAL_ID__CL,
j387.CL___MUX_LOCAL_ID__CL AS CL___MUX_LOCAL_ID__CL,
j387.CL___CARD_NO__CL AS CL___CARD_NO__CL,
j387.CL___CARD_NO__CL AS CL___CARD_NO__CL,
j387.CL___CARD_NO__CL AS CL___CARD_NO__CL,
j387.CL___PORT_NO__CL AS CL___PORT_NO__CL,
j387.CL___PORT_NO__CL AS CL___PORT_NO__CL,
j387.CL___PORT_NO__CL AS CL___PORT_NO__CL,
j388.CL___OBJECT__CL AS CL___OBJECT__CL,
src.CL___OBJ_INSTANCE__CL,
src.CL___ST_PORT_VALUE__CL,
src.CL___VALID_OBJ__CL,
LOWER(RAWTOHEX(STANDARD_HASH(TRIM(CAST(src.CL___PROXY_CODE__CL AS VARCHAR2(100))) || '|' || TRIM(CAST(src.CL___MUX_NO__CL AS VARCHAR2(100))) || '|' || TRIM(CAST(src.CL___MUX_LOCAL_ID__CL AS VARCHAR2(100))) || '|' || TRIM(CAST(src.CL___CARD_NO__CL AS VARCHAR2(100))) || '|' || TRIM(CAST(src.CL___PORT_NO__CL AS VARCHAR2(100))) || '|' || TRIM(CAST(src.CL___OBJECT__CL AS VARCHAR2(100))) || '|' || TRIM(CAST(src.CL___OBJ_INSTANCE__CL AS VARCHAR2(100))), 'MD5'))) AS ERP_CODE
FROM OI.TB___ST_PORTS__TB src
LEFT JOIN CLARO.TB___PORTS__TB j387 ON j387.ERP_CODE = LOWER(RAWTOHEX(STANDARD_HASH(TRIM(CAST(src.CL___CARD_NO__CL AS VARCHAR2(100))) || '|' || TRIM(CAST(src.CL___MUX_LOCAL_ID__CL AS VARCHAR2(100))) || '|' || TRIM(CAST(src.CL___MUX_NO__CL AS VARCHAR2(100))) || '|' || TRIM(CAST(src.CL___PORT_NO__CL AS VARCHAR2(100))) || '|' || TRIM(CAST(src.CL___PROXY_CODE__CL AS VARCHAR2(100))), 'MD5')))
LEFT JOIN CLARO.TB___OBJECTS__TB j388 ON j388.CL___OBJECT__CL = src.CL___OBJECT__CL
WHERE NOT EXISTS (SELECT 1 FROM CLARO.TB___ST_PORTS__TB dest WHERE dest.ERP_CODE = LOWER(RAWTOHEX(STANDARD_HASH(TRIM(CAST(src.CL___PROXY_CODE__CL AS VARCHAR2(100))) || '|' || TRIM(CAST(src.CL___MUX_NO__CL AS VARCHAR2(100))) || '|' || TRIM(CAST(src.CL___MUX_LOCAL_ID__CL AS VARCHAR2(100))) || '|' || TRIM(CAST(src.CL___CARD_NO__CL AS VARCHAR2(100))) || '|' || TRIM(CAST(src.CL___PORT_NO__CL AS VARCHAR2(100))) || '|' || TRIM(CAST(src.CL___OBJECT__CL AS VARCHAR2(100))) || '|' || TRIM(CAST(src.CL___OBJ_INSTANCE__CL AS VARCHAR2(100))), 'MD5'))));
