-- Ordem: 067 | Tabela: MS_SPRING_SQUELCH | Depth: 4
INSERT INTO MS_SPRING_SQUELCH
(
PROXY_CODE,
DEV_NO,
DEV_LOCAL_ID,
SLOT_NO,
PORT_NO,
WEST_SRC,
WEST_DST,
WEST_DST2,
WEST_LOVC,
EAST_SRC,
EAST_DST,
EAST_DST2,
EAST_LOVC,
CONTROL,
NOVACOLUNA,
ERP_CODE
)
SELECT
j1.ID AS PROXY_CODE,
j2.ID AS DEV_NO,
j3.ID AS DEV_LOCAL_ID,
j4.ID AS SLOT_NO,
j5.ID AS PORT_NO,
src.WEST_SRC,
src.WEST_DST,
src.WEST_DST2,
src.WEST_LOVC,
src.EAST_SRC,
src.EAST_DST,
src.EAST_DST2,
src.EAST_LOVC,
src.CONTROL,
src.NOVACOLUNA,
src.AU4_NO AS ERP_CODE
FROM CLARO.MS_SPRING_SQUELCH src
LEFT JOIN TB___PORTS__TB j1 ON j1.ERP_CODE = src.PROXY_CODE
LEFT JOIN TB___PORTS__TB j2 ON j2.ERP_CODE = src.DEV_NO
LEFT JOIN TB___PORTS__TB j3 ON j3.ERP_CODE = src.DEV_LOCAL_ID
LEFT JOIN TB___PORTS__TB j4 ON j4.ERP_CODE = src.SLOT_NO
LEFT JOIN TB___PORTS__TB j5 ON j5.ERP_CODE = src.PORT_NO
WHERE NOT EXISTS (
    SELECT 1 FROM MS_SPRING_SQUELCH dest WHERE dest.ERP_CODE = src.AU4_NO
);
COMMIT;