-- Ordem: 068 | Tabela: PORTS_TESTS | Depth: 4
INSERT INTO PORTS_TESTS
(
PROXY_CODE,
DEV_NO,
DEV_LOCAL_ID,
SLOT_NO,
PORT_NO,
TEST_ID,
TEST_SRC,
TEST_START_TIME,
NOVACOLUNA,
ERP_CODE
)
SELECT
j1.ID AS PROXY_CODE,
j2.ID AS DEV_NO,
j3.ID AS DEV_LOCAL_ID,
j4.ID AS SLOT_NO,
j5.ID AS PORT_NO,
src.TEST_ID,
src.TEST_SRC,
src.TEST_START_TIME,
src.NOVACOLUNA,
src.DEV_LOCAL_ID AS ERP_CODE
FROM CLARO.PORTS_TESTS src
LEFT JOIN TB___PORTS__TB j1 ON j1.ERP_CODE = src.PROXY_CODE
LEFT JOIN TB___PORTS__TB j2 ON j2.ERP_CODE = src.DEV_NO
LEFT JOIN TB___PORTS__TB j3 ON j3.ERP_CODE = src.DEV_LOCAL_ID
LEFT JOIN TB___PORTS__TB j4 ON j4.ERP_CODE = src.SLOT_NO
LEFT JOIN TB___PORTS__TB j5 ON j5.ERP_CODE = src.PORT_NO
WHERE NOT EXISTS (
    SELECT 1 FROM PORTS_TESTS dest WHERE dest.ERP_CODE = src.DEV_LOCAL_ID
);
COMMIT;