-- Ordem: 068 | Tabela: TIME_SLOT_PORT | Depth: 4
INSERT INTO CLARO.TIME_SLOT_PORT (
PORT_RESOURCE_ID,
PORT_RESOURCE_ID,
PORT_RESOURCE_ID,
TS_ID,
TS_ID,
TS_ID
)
SELECT 
j408.RESOURCE_ID AS PORT_RESOURCE_ID,
j408.RESOURCE_ID AS PORT_RESOURCE_ID,
j408.RESOURCE_ID AS PORT_RESOURCE_ID,
j409.ID AS TS_ID,
j409.ID AS TS_ID,
j409.ID AS TS_ID
FROM OI.TIME_SLOT_PORT src
LEFT JOIN CLARO.TB___PORTS__TB j408 ON j408.ERP_CODE = TRIM(CAST(src.PORT_RESOURCE_ID AS VARCHAR2(64)))
LEFT JOIN CLARO.TIME_SLOT j409 ON j409.ERP_CODE = TRIM(CAST(src.TS_ID AS VARCHAR2(64)))
WHERE NOT EXISTS (SELECT 1 FROM CLARO.TIME_SLOT_PORT dest WHERE dest.ERP_CODE = LOWER(RAWTOHEX(STANDARD_HASH(TRIM(CAST(src.PORT_RESOURCE_ID AS VARCHAR2(100))) || '|' || TRIM(CAST(src.TS_ID AS VARCHAR2(100))), 'MD5'))));
COMMIT;