-- Ordem: 069 | Tabela: SHORTCUT_NODE | Depth: 4
INSERT INTO SHORTCUT_NODE
(
SHORTCUT_NODE_TARGET,
NOVACOLUNA,
ERP_CODE
)
SELECT
j2.ID AS SHORTCUT_NODE_TARGET,
src.NOVACOLUNA,
src.GRAPHIC_ID AS ERP_CODE
FROM CLARO.SHORTCUT_NODE src
LEFT JOIN NODE j1 ON j1.ERP_CODE = src.GRAPHIC_ID
LEFT JOIN GROUP_NODE j2 ON j2.ERP_CODE = src.SHORTCUT_NODE_TARGET
WHERE NOT EXISTS (
    SELECT 1 FROM SHORTCUT_NODE dest WHERE dest.ERP_CODE = src.GRAPHIC_ID
);
COMMIT;