-- Ordem: 069 | Tabela: CONNECTION_LINKS | Depth: 5
INSERT INTO CLARO.CONNECTION_LINKS (
GRAPHIC_ID,
LINK_ID
)
SELECT 
j92.GRAPHIC_ID AS GRAPHIC_ID,
j91.LINK_ID AS LINK_ID
FROM OI.CONNECTION_LINKS src
LEFT JOIN CLARO.LINK j91 ON j91.ERP_CODE = TRIM(CAST(src.LINK_ID AS VARCHAR2(64)))
LEFT JOIN CLARO.CONNECTION j92 ON j92.ERP_CODE = TRIM(CAST(src.GRAPHIC_ID AS VARCHAR2(64)))
WHERE NOT EXISTS (SELECT 1 FROM CLARO.CONNECTION_LINKS dest WHERE dest.ERP_CODE = LOWER(RAWTOHEX(STANDARD_HASH(TRIM(CAST(src.GRAPHIC_ID AS VARCHAR2(100))) || '|' || TRIM(CAST(src.LINK_ID AS VARCHAR2(100))), 'MD5'))));
COMMIT;