-- Ordem: 070 | Tabela: PORT_LINK | Depth: 5
INSERT INTO CLARO.PORT_LINK (
LINK_ID,
WEIGHT,
LINK_TYPE,
A_END_PORT_PROXY_CODE,
A_END_PORT_DEV_NO,
A_END_PORT_DEV_LOCAL_ID,
A_END_PORT_PORT_NO,
Z_END_PORT_PROXY_CODE,
Z_END_PORT_DEV_NO,
Z_END_PORT_DEV_LOCAL_ID,
Z_END_PORT_PORT_NO,
RESOURCE_ID,
BLOCKED,
A_END_PORT_RESOURCE_ID,
Z_END_PORT_RESOURCE_ID,
A_END_PORT_SLOT_NO,
Z_END_PORT_SLOT_NO,
A_END_PORT_MODEL,
Z_END_PORT_MODEL,
A_END_PORT_CHASSIS_ID,
Z_END_PORT_CHASSIS_ID,
ERP_CODE
)
SELECT 
j235.LINK_ID AS LINK_ID,
src.WEIGHT,
j234.ID_PORT_LINK_TYPE AS LINK_TYPE,
src.A_END_PORT_PROXY_CODE,
src.A_END_PORT_DEV_NO,
src.A_END_PORT_DEV_LOCAL_ID,
src.A_END_PORT_PORT_NO,
src.Z_END_PORT_PROXY_CODE,
src.Z_END_PORT_DEV_NO,
src.Z_END_PORT_DEV_LOCAL_ID,
src.Z_END_PORT_PORT_NO,
j233.RESOURCE_ID AS RESOURCE_ID,
src.BLOCKED,
src.A_END_PORT_RESOURCE_ID,
src.Z_END_PORT_RESOURCE_ID,
src.A_END_PORT_SLOT_NO,
src.Z_END_PORT_SLOT_NO,
src.A_END_PORT_MODEL,
src.Z_END_PORT_MODEL,
src.A_END_PORT_CHASSIS_ID,
src.Z_END_PORT_CHASSIS_ID,
TRIM(CAST(src.LINK_ID AS VARCHAR2(64))) AS ERP_CODE
FROM OI.PORT_LINK src
LEFT JOIN CLARO.PROVISIONING_RESOURCE j233 ON j233.ERP_CODE = TRIM(CAST(src.RESOURCE_ID AS VARCHAR2(64)))
LEFT JOIN CLARO.PORT_LINK_TYPE j234 ON j234.ID_PORT_LINK_TYPE = src.LINK_TYPE
LEFT JOIN CLARO.LINK j235 ON j235.ERP_CODE = TRIM(CAST(src.LINK_ID AS VARCHAR2(64)))
WHERE NOT EXISTS (SELECT 1 FROM CLARO.PORT_LINK dest WHERE dest.ERP_CODE = TRIM(CAST(src.LINK_ID AS VARCHAR2(64))));
