-- Ordem: 070 | Tabela: STP_PROTECTED_VLAN_GROUPS | Depth: 4
INSERT INTO STP_PROTECTED_VLAN_GROUPS
(
STP_CFG_ID,
VLAN_GROUPS_BITMAP,
NOVACOLUNA,
ERP_CODE
)
SELECT
j1.ID AS STP_CFG_ID,
src.VLAN_GROUPS_BITMAP,
src.NOVACOLUNA,
src.BITMAP_INDEX AS ERP_CODE
FROM CLARO.STP_PROTECTED_VLAN_GROUPS src
LEFT JOIN STP_CFG j1 ON j1.ERP_CODE = src.STP_CFG_ID
WHERE NOT EXISTS (
    SELECT 1 FROM STP_PROTECTED_VLAN_GROUPS dest WHERE dest.ERP_CODE = src.BITMAP_INDEX
);
COMMIT;