-- Ordem: 071 | Tabela: LINK_PATH_SECTION | Depth: 6
INSERT INTO CLARO.LINK_PATH_SECTION (
ID_PATH_SECTION,
ID_LINK,
ERP_CODE
)
SELECT 
j156.ID_PATH_SECTION AS ID_PATH_SECTION,
j155.LINK_ID AS ID_LINK,
LOWER(RAWTOHEX(STANDARD_HASH(TRIM(CAST(src.ID_PATH_SECTION AS VARCHAR2(100))) || '|' || TRIM(CAST(src.ID_LINK AS VARCHAR2(100))), 'MD5'))) AS ERP_CODE
FROM OI.LINK_PATH_SECTION src
LEFT JOIN CLARO.PORT_LINK j155 ON j155.ERP_CODE = TRIM(CAST(src.ID_LINK AS VARCHAR2(64)))
LEFT JOIN CLARO.PATH_SECTION j156 ON j156.ERP_CODE = TRIM(CAST(src.ID_PATH_SECTION AS VARCHAR2(64)))
WHERE NOT EXISTS (SELECT 1 FROM CLARO.LINK_PATH_SECTION dest WHERE dest.ERP_CODE = LOWER(RAWTOHEX(STANDARD_HASH(TRIM(CAST(src.ID_PATH_SECTION AS VARCHAR2(100))) || '|' || TRIM(CAST(src.ID_LINK AS VARCHAR2(100))), 'MD5'))));
