-- Ordem: 071 | Tabela: TB___CFG_PORTS__TB | Depth: 4
INSERT INTO TB___CFG_PORTS__TB
(
CL___PROXY_CODE__CL,
CL___MUX_NO__CL,
CL___MUX_LOCAL_ID__CL,
CL___PORT_NO__CL,
CL___OBJECT__CL,
CL___OBJ_INSTANCE__CL,
CL___CFG_PORT_VALUE__CL,
CL___UPDATE_DEV__CL,
CL___VALID_OBJ__CL,
NOVACOLUNA,
ERP_CODE
)
SELECT
j1.ID AS CL___PROXY_CODE__CL,
j2.ID AS CL___MUX_NO__CL,
j3.ID AS CL___MUX_LOCAL_ID__CL,
j5.ID AS CL___PORT_NO__CL,
j6.ID AS CL___OBJECT__CL,
src.CL___OBJ_INSTANCE__CL,
src.CL___CFG_PORT_VALUE__CL,
src.CL___UPDATE_DEV__CL,
src.CL___VALID_OBJ__CL,
src.NOVACOLUNA,
src.CL___CARD_NO__CL AS ERP_CODE
FROM CLARO.TB___CFG_PORTS__TB src
LEFT JOIN TB___PORTS__TB j1 ON j1.ERP_CODE = src.CL___PROXY_CODE__CL
LEFT JOIN TB___PORTS__TB j2 ON j2.ERP_CODE = src.CL___MUX_NO__CL
LEFT JOIN TB___PORTS__TB j3 ON j3.ERP_CODE = src.CL___MUX_LOCAL_ID__CL
LEFT JOIN TB___PORTS__TB j4 ON j4.ERP_CODE = src.CL___CARD_NO__CL
LEFT JOIN TB___PORTS__TB j5 ON j5.ERP_CODE = src.CL___PORT_NO__CL
LEFT JOIN TB___OBJECTS__TB j6 ON j6.ID = src.CL___OBJECT__CL
WHERE NOT EXISTS (
    SELECT 1 FROM TB___CFG_PORTS__TB dest WHERE dest.ERP_CODE = src.CL___CARD_NO__CL
);
COMMIT;