-- Ordem: 072 | Tabela: TB___PORTS_ALARMS__TB | Depth: 4
INSERT INTO TB___PORTS_ALARMS__TB
(
CL___PROXY_CODE__CL,
CL___MUX_NO__CL,
CL___MUX_LOCAL_ID__CL,
CL___CARD_NO__CL,
CL___PORT_NO__CL,
CL___ALARM_ID__CL,
UPTIME,
NOVACOLUNA,
ERP_CODE
)
SELECT
j1.ID AS CL___PROXY_CODE__CL,
j2.ID AS CL___MUX_NO__CL,
j3.ID AS CL___MUX_LOCAL_ID__CL,
j4.ID AS CL___CARD_NO__CL,
j5.ID AS CL___PORT_NO__CL,
j6.ID AS CL___ALARM_ID__CL,
src.UPTIME,
src.NOVACOLUNA,
src.CL___ALARM_ID__CL AS ERP_CODE
FROM CLARO.TB___PORTS_ALARMS__TB src
LEFT JOIN TB___PORTS__TB j1 ON j1.ERP_CODE = src.CL___PROXY_CODE__CL
LEFT JOIN TB___PORTS__TB j2 ON j2.ERP_CODE = src.CL___MUX_NO__CL
LEFT JOIN TB___PORTS__TB j3 ON j3.ERP_CODE = src.CL___MUX_LOCAL_ID__CL
LEFT JOIN TB___PORTS__TB j4 ON j4.ERP_CODE = src.CL___CARD_NO__CL
LEFT JOIN TB___PORTS__TB j5 ON j5.ERP_CODE = src.CL___PORT_NO__CL
LEFT JOIN TB___ALARMS__TB j6 ON j6.ID = src.CL___ALARM_ID__CL
WHERE NOT EXISTS (
    SELECT 1 FROM TB___PORTS_ALARMS__TB dest WHERE dest.ERP_CODE = src.CL___ALARM_ID__CL
);
COMMIT;