-- Ordem: 074 | Tabela: TIME_SLOT_PORT | Depth: 4
INSERT INTO TIME_SLOT_PORT
(
TS_ID,
NOVACOLUNA,
ERP_CODE
)
SELECT
j2.ID AS TS_ID,
src.NOVACOLUNA,
src.PORT_RESOURCE_ID AS ERP_CODE
FROM CLARO.TIME_SLOT_PORT src
LEFT JOIN TB___PORTS__TB j1 ON j1.ERP_CODE = src.PORT_RESOURCE_ID
LEFT JOIN TIME_SLOT j2 ON j2.ERP_CODE = src.TS_ID
WHERE NOT EXISTS (
    SELECT 1 FROM TIME_SLOT_PORT dest WHERE dest.ERP_CODE = src.PORT_RESOURCE_ID
);
COMMIT;