-- Ordem: 075 | Tabela: CONNECTION_LINKS | Depth: 5
INSERT INTO CONNECTION_LINKS
(
LINK_ID,
NOVACOLUNA,
ERP_CODE
)
SELECT
j2.ID AS LINK_ID,
src.NOVACOLUNA,
src.GRAPHIC_ID AS ERP_CODE
FROM CLARO.CONNECTION_LINKS src
LEFT JOIN CONNECTION j1 ON j1.ERP_CODE = src.GRAPHIC_ID
LEFT JOIN LINK j2 ON j2.ERP_CODE = src.LINK_ID
WHERE NOT EXISTS (
    SELECT 1 FROM CONNECTION_LINKS dest WHERE dest.ERP_CODE = src.GRAPHIC_ID
);
COMMIT;