-- Ordem: 076 | Tabela: PORT_LINK | Depth: 5
INSERT INTO PORT_LINK
(
WEIGHT,
LINK_TYPE,
A_END_PORT_PROXY_CODE,
A_END_PORT_DEV_NO,
A_END_PORT_DEV_LOCAL_ID,
A_END_PORT_PORT_NO,
Z_END_PORT_PROXY_CODE,
Z_END_PORT_DEV_NO,
Z_END_PORT_DEV_LOCAL_ID,
Z_END_PORT_PORT_NO,
RESOURCE_ID,
BLOCKED,
A_END_PORT_RESOURCE_ID,
Z_END_PORT_RESOURCE_ID,
A_END_PORT_SLOT_NO,
Z_END_PORT_SLOT_NO,
A_END_PORT_MODEL,
Z_END_PORT_MODEL,
A_END_PORT_CHASSIS_ID,
Z_END_PORT_CHASSIS_ID,
NOVACOLUNA,
ERP_CODE
)
SELECT
src.WEIGHT,
j3.ID AS LINK_TYPE,
src.A_END_PORT_PROXY_CODE,
src.A_END_PORT_DEV_NO,
src.A_END_PORT_DEV_LOCAL_ID,
src.A_END_PORT_PORT_NO,
src.Z_END_PORT_PROXY_CODE,
src.Z_END_PORT_DEV_NO,
src.Z_END_PORT_DEV_LOCAL_ID,
src.Z_END_PORT_PORT_NO,
j12.ID AS RESOURCE_ID,
src.BLOCKED,
src.A_END_PORT_RESOURCE_ID,
src.Z_END_PORT_RESOURCE_ID,
src.A_END_PORT_SLOT_NO,
src.Z_END_PORT_SLOT_NO,
src.A_END_PORT_MODEL,
src.Z_END_PORT_MODEL,
src.A_END_PORT_CHASSIS_ID,
src.Z_END_PORT_CHASSIS_ID,
src.NOVACOLUNA,
src.LINK_ID AS ERP_CODE
FROM CLARO.PORT_LINK src
LEFT JOIN LINK j1 ON j1.ERP_CODE = src.LINK_ID
LEFT JOIN PORT_LINK_TYPE j3 ON j3.ID = src.LINK_TYPE
LEFT JOIN PROVISIONING_RESOURCE j12 ON j12.ERP_CODE = src.RESOURCE_ID
WHERE NOT EXISTS (
    SELECT 1 FROM PORT_LINK dest WHERE dest.ERP_CODE = src.LINK_ID
);
COMMIT;