-- Ordem: 077 | Tabela: LINK_PATH_SECTION | Depth: 6
INSERT INTO LINK_PATH_SECTION
(
ID_PATH_SECTION,
NOVACOLUNA,
ERP_CODE
)
SELECT
j1.ID AS ID_PATH_SECTION,
src.NOVACOLUNA,
src.ID_LINK AS ERP_CODE
FROM CLARO.LINK_PATH_SECTION src
LEFT JOIN PATH_SECTION j1 ON j1.ERP_CODE = src.ID_PATH_SECTION
LEFT JOIN PORT_LINK j2 ON j2.ERP_CODE = src.ID_LINK
WHERE NOT EXISTS (
    SELECT 1 FROM LINK_PATH_SECTION dest WHERE dest.ERP_CODE = src.ID_LINK
);
COMMIT;