
WITH params AS (
    SELECT 'CLARO' AS schema_destino FROM dual
),
target_tables AS (
    SELECT 'CIRCUIT_END' as table_name FROM dual UNION ALL
    SELECT 'CIRCUIT_FILTER' FROM dual UNION ALL
    SELECT 'CIRCUIT_PORT_END' FROM dual UNION ALL
    SELECT 'CUSTOMER' FROM dual UNION ALL
    SELECT 'DEVICE_DATA_FILE' FROM dual UNION ALL
    SELECT 'GRAPHIC' FROM dual UNION ALL
    SELECT 'LINK' FROM dual UNION ALL
    SELECT 'MATRIX' FROM dual UNION ALL
    SELECT 'NODE' FROM dual UNION ALL
    SELECT 'PATH' FROM dual UNION ALL
    SELECT 'PATH_SECTION' FROM dual UNION ALL
    SELECT 'PORT_PATH_SECTION' FROM dual UNION ALL
    SELECT 'SDH_MAPPING' FROM dual UNION ALL
    SELECT 'SDH_MAPPING_DM800' FROM dual UNION ALL
    SELECT 'SERVICE' FROM dual UNION ALL
    SELECT 'SNMP' FROM dual UNION ALL
    SELECT 'SNMPV1_2' FROM dual UNION ALL
    SELECT 'STP_CFG' FROM dual UNION ALL
    SELECT 'TB___PROXIES__TB' FROM dual UNION ALL
    SELECT 'TIME_SLOT' FROM dual UNION ALL
    SELECT 'VLAN_CFG' FROM dual UNION ALL
    SELECT 'CIRCUIT_FILTER_PROPERTY' FROM dual UNION ALL
    SELECT 'CIRCUIT_PATH_SECTION' FROM dual
)
SELECT 
    'DROP TRIGGER ' || (SELECT schema_destino FROM params) || '.TRG_BI_' || table_name || ';' as drop_script
FROM target_tables;
